'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase';
import ThreeDArt from '@/components/ThreeDArt';
import type { StoreSettings } from '@/lib/types';
export default function OwnerLogin(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [msg,setMsg]=useState('');const [settings,setSettings]=useState<Partial<StoreSettings>>({});const router=useRouter();
 useEffect(()=>{createClient().from('store_settings').select('brand_name,logo_url,owner_login_label,owner_login_heading,owner_login_description').eq('id',1).maybeSingle().then(({data})=>{if(data)setSettings(data)})},[]);
 async function submit(e:FormEvent){e.preventDefault();setMsg('Memproses...');const s=createClient();const {error}=await s.auth.signInWithPassword({email,password});if(error)return setMsg(error.message);const {data:isAdmin,error:roleError}=await s.rpc('is_admin');if(roleError||!isAdmin){await s.auth.signOut();return setMsg('Akun ini bukan owner toko. Pada instalasi baru, akun Authentication pertama otomatis menjadi owner.')}router.replace('/admin')}
 const brand=settings.brand_name||'Digital Store';const initial=brand.trim().charAt(0).toUpperCase()||'S';
 return <div className="themeRoot authPage"><div className="authCard glass"><div className="authArt"><ThreeDArt/></div><div className="authForm"><div className="brand">{settings.logo_url?<img src={settings.logo_url} alt={brand} style={{maxWidth:46,maxHeight:46,objectFit:'contain',borderRadius:12}}/>:<span className="logo">{initial}</span>}<span>{brand} {settings.owner_login_label||'Owner'}</span></div><h1 style={{fontSize:42,marginBottom:8}}>{settings.owner_login_heading||'Owner Login'}</h1><p className="muted">{settings.owner_login_description||'Halaman privat pemilik toko.'}</p><form className="form" onSubmit={submit}><div className="field"><label>Email</label><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="field"><label>Password</label><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></div><button className="btn">Masuk Owner</button>{msg&&<div className="notice">{msg}</div>}</form></div></div></div>}
