'use client';
import { useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase';
import { Order } from '@/lib/types';
import { rupiah } from '@/lib/money';
import ConfirmDialog from '@/components/ConfirmDialog';
export default function Orders(){
 const [rows,setRows]=useState<Order[]>([]),[filter,setFilter]=useState('all'),[q,setQ]=useState(''),[page,setPage]=useState(1),[size,setSize]=useState(10),[msg,setMsg]=useState('');
 const [statusChange,setStatusChange]=useState<{id:string;from:Order['status'];to:Order['status'];order:string}|null>(null),[statusBusy,setStatusBusy]=useState(false);
 async function load(){const {data}=await createClient().from('orders').select('*,products(name,slug,image_url),order_items(id,order_id,product_id,product_name,price,quantity,subtotal,products(name,slug,image_url))').order('created_at',{ascending:false});setRows((data||[]) as Order[])} useEffect(()=>{load()},[]);
 function askStatus(o:Order,v:Order['status']){if(v===o.status)return;setStatusChange({id:o.id,from:o.status,to:v,order:o.order_number})}
 async function confirmStatus(){if(!statusChange)return;setStatusBusy(true);const {error}=await createClient().from('orders').update({status:statusChange.to}).eq('id',statusChange.id);setStatusBusy(false);if(error){setMsg(error.message);return}setMsg(`Status order ${statusChange.order} diperbarui menjadi ${statusChange.to}.`);setStatusChange(null);await load()}
 const filtered=useMemo(()=>rows.filter(x=>(filter==='all'||x.status===filter)&&`${x.order_number} ${x.customer_name} ${x.customer_email} ${x.customer_whatsapp} ${x.products?.name||''} ${(x.order_items||[]).map(i=>i.product_name).join(' ')}`.toLowerCase().includes(q.toLowerCase())),[rows,filter,q]);
 const pages=Math.max(1,Math.ceil(filtered.length/size)),safePage=Math.min(page,pages),shown=filtered.slice((safePage-1)*size,safePage*size);
 return <><ConfirmDialog open={!!statusChange} title="Ubah Status Order?" message={statusChange?`Status ${statusChange.order} akan diubah dari ${statusChange.from} menjadi ${statusChange.to}.`:''} confirmText="Ya, Ubah Status" busy={statusBusy} onCancel={()=>!statusBusy&&setStatusChange(null)} onConfirm={confirmStatus}/><div className="pageHead3d"><div><span className="eyebrow">INTERNAL CHECKOUT</span><h1>Order / Checkout</h1><p>Kelola pembayaran customer yang checkout langsung di website.</p></div></div><div className="filterPanel3d"><input className="input" placeholder="Cari order, customer, email, WA, produk..." value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/><select className="input" value={filter} onChange={e=>{setFilter(e.target.value);setPage(1)}}><option value="all">Semua Status</option><option value="pending">Pending</option><option value="paid">Paid</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><select className="input" value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}><option value="10">10 / halaman</option><option value="20">20 / halaman</option><option value="50">50 / halaman</option></select></div><div className="orderCards3d">{shown.map(o=><article className="orderCard3d" key={o.id}><div className="orderMain"><div><span className={`statusPill ${o.status}`}>{o.status}</span><h3>{(o.order_items?.length||0)>1?`${o.order_items!.length} Produk`:o.order_items?.[0]?.product_name||o.products?.name||'Produk'}</h3>{o.order_items&&o.order_items.length>0&&<div className="orderItemMiniList">{o.order_items.map(i=><span key={i.id}>• {i.product_name} — {rupiah(i.subtotal)}</span>)}</div>}<p>{o.customer_name} • {o.customer_email}</p><small>{o.order_number} • {new Date(o.created_at).toLocaleString('id-ID')}</small></div><div className="orderAmount"><strong>{rupiah(o.amount)}</strong><span>{o.payment_method}</span></div></div><div className="orderActions"><a className="btn alt" href={`https://wa.me/${o.customer_whatsapp.replace(/\D/g,'')}`} target="_blank">WhatsApp</a>{o.payment_proof_url&&<a className="btn alt" href={o.payment_proof_url} target="_blank">Bukti Bayar</a>}<select className="input" value={o.status} onChange={e=>askStatus(o,e.target.value as Order['status'])}><option value="pending">Pending</option><option value="paid">Paid</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div></article>)}{!shown.length&&<div className="empty3d panel3d">Belum ada order.</div>}</div><div className="pager3d"><span>{filtered.length} order • Halaman {safePage}/{pages}</span><div className="actions"><button type="button" className="btn alt" disabled={safePage<=1} onClick={()=>setPage(x=>Math.max(1,x-1))}>←</button><button type="button" className="btn alt" disabled={safePage>=pages} onClick={()=>setPage(x=>Math.min(pages,x+1))}>→</button></div></div>{msg&&<div className="notice floatingNotice">{msg}</div>}</>
}
