'use client';
import { FormEvent, useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase';
import { StoreSettings } from '@/lib/types';
import { THEME_PRESETS } from '@/lib/themes';

const base:StoreSettings={id:1,brand_name:'Digital Store',tagline:'Digital product store',logo_url:null,favicon_url:null,whatsapp:null,instagram_url:null,primary_color:'#8b5cf6',secondary_color:'#c4b5fd',accent_color:'#f9a8d4',theme_preset:'lavender',hero_badge:'BONUS EKSKLUSIF',hero_title:'Produk Digital Siap Jual untuk Member ADC',hero_subtitle:'Temukan produk digital pilihan dan beli melalui link affiliate resmi.',hero_primary_cta_text:'Lihat Produk',hero_member_cta_text:'Masuk Member',hero_member_cta_enabled:true,hero_trust_1:'Produk siap promosi',hero_trust_2:'Link affiliate sendiri',hero_trust_3:'Tema bisa diganti',hero_visual_mode:'default',hero_image_url:null,hero_image_position:'right',hero_image_fit:'contain',hero_image_alt:'Hero image',catalog_eyebrow:'KATALOG DIGITAL',catalog_title:'Produk pilihan untuk mulai jualan',catalog_subtitle:'Produk ADC sudah tersedia. Pemilik toko tinggal mengatur link affiliate masing-masing.',floating_wa_enabled:false,floating_wa_number:null,floating_wa_message:'Halo, saya butuh bantuan tentang produk ini.',floating_wa_position:'right',floating_wa_style:'3d',floating_wa_icon_url:null,floating_wa_tooltip:'Butuh bantuan? Chat WhatsApp',floating_wa_show_on:'all',footer_text:'Digital Store',home_products_per_page:8,pwa_name:'Digital Store',pwa_short_name:'Store',pwa_icon_url:null,member_login_label:'Member',member_login_heading:'Welcome Back!',member_login_description:'Masuk untuk membuka member area dan mengatur tema pribadi Anda.',member_signup_heading:'Buat Akun Member',member_signup_description:'Daftar untuk mengakses member area.',owner_login_label:'Owner',owner_login_heading:'Owner Login',owner_login_description:'Halaman privat pemilik toko.',admin_console_label:'Owner Console'};

export default function Settings(){
 const [d,setD]=useState(base),[msg,setMsg]=useState(''),[pwd,setPwd]=useState(''),[uploading,setUploading]=useState('');
 useEffect(()=>{createClient().from('store_settings').select('*').eq('id',1).maybeSingle().then(({data})=>{if(data)setD({...base,...data} as StoreSettings)})},[]);
 function pickTheme(id:string){const t=THEME_PRESETS.find(x=>x.id===id)!;setD({...d,theme_preset:id,primary_color:t.primary,secondary_color:t.secondary,accent_color:t.accent})}
 async function save(e:FormEvent){e.preventDefault();const {error}=await createClient().from('store_settings').upsert(d);setMsg(error?error.message:'Pengaturan dan tema berhasil disimpan.')}
 async function changePass(){if(pwd.length<6){setMsg('Password minimal 6 karakter.');return}const {error}=await createClient().auth.updateUser({password:pwd});setMsg(error?error.message:'Password owner berhasil diganti.');if(!error)setPwd('')}
 async function uploadAsset(file:File,kind:'hero'|'wa'|'pwa'|'logo'|'favicon'){
   setUploading(kind);setMsg('');
   const ext=(file.name.split('.').pop()||'png').toLowerCase();
   const path=`settings/${kind}-${Date.now()}.${ext}`;
   const s=createClient();
   const {error}=await s.storage.from('store-assets').upload(path,file,{upsert:false,contentType:file.type||undefined});
   if(error){setMsg(error.message);setUploading('');return}
   const {data}=s.storage.from('store-assets').getPublicUrl(path);
   if(kind==='hero')setD(x=>({...x,hero_visual_mode:'upload',hero_image_url:data.publicUrl}));
   else if(kind==='wa')setD(x=>({...x,floating_wa_style:'custom',floating_wa_icon_url:data.publicUrl}));
   else if(kind==='pwa')setD(x=>({...x,pwa_icon_url:data.publicUrl}));
   else if(kind==='logo')setD(x=>({...x,logo_url:data.publicUrl}));
   else setD(x=>({...x,favicon_url:data.publicUrl}));
   setUploading('');setMsg('Upload berhasil. Klik Simpan Pengaturan agar perubahan tersimpan.');
 }
 return <><div className="topline"><div><h1>Pengaturan Toko</h1><p className="muted">Branding, homepage, login, favicon, WhatsApp melayang, PWA, dan tema warna toko.</p></div></div>
 <form className="form glass" onSubmit={save} style={{padding:24,borderRadius:26,maxWidth:980}}>
  <h2 style={{marginBottom:0}}>Branding</h2>
  <div className="twoCols"><div className="field"><label>Upload Logo Brand</label><input className="input" type="file" accept="image/*" disabled={uploading==='logo'} onChange={e=>{const f=e.target.files?.[0];if(f)uploadAsset(f,'logo')}}/><small className="muted">Logo ini dipakai di navbar, login, member area, dan dashboard owner.</small></div><div className="field"><label>Logo URL</label><input className="input" value={d.logo_url||''} onChange={e=>setD({...d,logo_url:e.target.value})} placeholder="https://..."/></div></div>
  {d.logo_url&&<img src={d.logo_url} alt="Logo preview" style={{maxWidth:180,maxHeight:80,objectFit:'contain',marginBottom:12}}/>}
  <div className="twoCols"><div className="field"><label>Upload Favicon</label><input className="input" type="file" accept="image/png,image/webp,image/jpeg,image/x-icon" disabled={uploading==='favicon'} onChange={e=>{const f=e.target.files?.[0];if(f)uploadAsset(f,'favicon')}}/><small className="muted">Rekomendasi square 64×64 atau 128×128. Jika kosong, otomatis pakai Logo Brand.</small></div><div className="field"><label>Favicon URL</label><input className="input" value={d.favicon_url||''} onChange={e=>setD({...d,favicon_url:e.target.value})} placeholder="https://..."/></div></div>
  {[['Nama Brand','brand_name'],['Tagline','tagline'],['WhatsApp Utama','whatsapp'],['Instagram URL','instagram_url'],['Footer Text','footer_text']].map(([label,key])=><div className="field" key={key}><label>{label}</label><input className="input" value={(d as any)[key]||''} onChange={e=>setD({...d,[key]:e.target.value})}/></div>)}

  <div className="panel3d" style={{padding:20,marginTop:10}}><h2 style={{marginTop:0}}>Login & Area Brand</h2><p className="muted">Semua label login mengikuti brand dan bisa diedit. Logo memakai Logo Brand di atas.</p>
   <div className="field"><label>Label Login Member</label><input className="input" value={d.member_login_label||''} onChange={e=>setD({...d,member_login_label:e.target.value})} placeholder="Member"/></div>
   <div className="twoCols"><div className="field"><label>Heading Login Member</label><input className="input" value={d.member_login_heading||''} onChange={e=>setD({...d,member_login_heading:e.target.value})}/></div><div className="field"><label>Heading Daftar Member</label><input className="input" value={d.member_signup_heading||''} onChange={e=>setD({...d,member_signup_heading:e.target.value})}/></div></div>
   <div className="twoCols"><div className="field"><label>Deskripsi Login Member</label><textarea className="input" rows={2} value={d.member_login_description||''} onChange={e=>setD({...d,member_login_description:e.target.value})}/></div><div className="field"><label>Deskripsi Daftar Member</label><textarea className="input" rows={2} value={d.member_signup_description||''} onChange={e=>setD({...d,member_signup_description:e.target.value})}/></div></div>
   <div className="twoCols"><div className="field"><label>Label Owner</label><input className="input" value={d.owner_login_label||''} onChange={e=>setD({...d,owner_login_label:e.target.value})}/></div><div className="field"><label>Label Dashboard Owner</label><input className="input" value={d.admin_console_label||''} onChange={e=>setD({...d,admin_console_label:e.target.value})}/></div></div>
   <div className="field"><label>Heading Login Owner</label><input className="input" value={d.owner_login_heading||''} onChange={e=>setD({...d,owner_login_heading:e.target.value})}/></div>
   <div className="field"><label>Deskripsi Login Owner</label><textarea className="input" rows={2} value={d.owner_login_description||''} onChange={e=>setD({...d,owner_login_description:e.target.value})}/></div>
  </div>

  <div className="panel3d" style={{padding:20,marginTop:10}}><h2 style={{marginTop:0}}>Homepage / Hero</h2><p className="muted">Semua teks di area hero dan katalog bisa diganti. Tidak hardcode lagi.</p>
   {[["Badge Hero","hero_badge"],["Hero Title","hero_title"],["Hero Subtitle","hero_subtitle"],["Teks CTA Utama","hero_primary_cta_text"],["Teks CTA Member","hero_member_cta_text"],["Highlight 1","hero_trust_1"],["Highlight 2","hero_trust_2"],["Highlight 3","hero_trust_3"],["Katalog Eyebrow","catalog_eyebrow"],["Judul Katalog","catalog_title"],["Subjudul Katalog","catalog_subtitle"]].map(([label,key])=><div className="field" key={key}><label>{label}</label><input className="input" value={(d as any)[key]||''} onChange={e=>setD({...d,[key]:e.target.value})}/></div>)}
   <label className="toggleLine"><input type="checkbox" checked={d.hero_member_cta_enabled} onChange={e=>setD({...d,hero_member_cta_enabled:e.target.checked})}/> Tampilkan tombol Masuk Member di hero</label>
   <div className="threeCols"><div className="field"><label>Tipe Visual Hero</label><select className="input" value={d.hero_visual_mode} onChange={e=>setD({...d,hero_visual_mode:e.target.value as StoreSettings['hero_visual_mode']})}><option value="default">Default 3D Illustration</option><option value="upload">Upload Image</option><option value="url">Image URL</option><option value="none">Tanpa Image</option></select></div><div className="field"><label>Posisi Image</label><select className="input" value={d.hero_image_position} onChange={e=>setD({...d,hero_image_position:e.target.value as StoreSettings['hero_image_position']})}><option value="right">Kanan</option><option value="left">Kiri</option></select></div><div className="field"><label>Object Fit</label><select className="input" value={d.hero_image_fit} onChange={e=>setD({...d,hero_image_fit:e.target.value as StoreSettings['hero_image_fit']})}><option value="contain">Contain</option><option value="cover">Cover</option></select></div></div>
   <div className="twoCols"><div className="field"><label>Upload Hero Image</label><input className="input" type="file" accept="image/*" disabled={uploading==='hero'} onChange={e=>{const f=e.target.files?.[0];if(f)uploadAsset(f,'hero')}}/><small className="muted">{uploading==='hero'?'Sedang upload...':'JPG, PNG, WEBP.'}</small></div><div className="field"><label>Hero Image URL</label><input className="input" value={d.hero_image_url||''} onChange={e=>setD({...d,hero_visual_mode:'url',hero_image_url:e.target.value})} placeholder="https://..."/></div></div>
   <div className="field"><label>Hero Image Alt Text</label><input className="input" value={d.hero_image_alt||''} onChange={e=>setD({...d,hero_image_alt:e.target.value})}/></div>
   {d.hero_image_url&&<div className="glass" style={{padding:14,borderRadius:18}}><img src={d.hero_image_url} alt="Hero preview" style={{maxWidth:360,width:'100%',maxHeight:220,objectFit:'contain',borderRadius:16}}/></div>}
  </div>

  <div className="panel3d" style={{padding:20,marginTop:10}}><h2 style={{marginTop:0}}>Floating WhatsApp</h2><p className="muted">Optional. Pengunjung bisa klik tombol WhatsApp melayang jika butuh bantuan.</p>
   <label className="toggleLine"><input type="checkbox" checked={d.floating_wa_enabled} onChange={e=>setD({...d,floating_wa_enabled:e.target.checked})}/> Aktifkan Floating WhatsApp</label>
   <div className="twoCols"><div className="field"><label>Nomor WhatsApp</label><input className="input" value={d.floating_wa_number||''} onChange={e=>setD({...d,floating_wa_number:e.target.value})} placeholder="62812..."/></div><div className="field"><label>Tooltip</label><input className="input" value={d.floating_wa_tooltip||''} onChange={e=>setD({...d,floating_wa_tooltip:e.target.value})} placeholder="Butuh bantuan? Chat WhatsApp"/></div></div>
   <div className="field"><label>Pesan Default</label><textarea className="input" rows={3} value={d.floating_wa_message||''} onChange={e=>setD({...d,floating_wa_message:e.target.value})}/></div>
   <div className="threeCols"><div className="field"><label>Posisi</label><select className="input" value={d.floating_wa_position} onChange={e=>setD({...d,floating_wa_position:e.target.value as StoreSettings['floating_wa_position']})}><option value="right">Kanan Bawah</option><option value="left">Kiri Bawah</option></select></div><div className="field"><label>Style</label><select className="input" value={d.floating_wa_style} onChange={e=>setD({...d,floating_wa_style:e.target.value as StoreSettings['floating_wa_style']})}><option value="3d">3D</option><option value="round">Bulat</option><option value="custom">Custom Image</option></select></div><div className="field"><label>Tampilkan di</label><select className="input" value={d.floating_wa_show_on} onChange={e=>setD({...d,floating_wa_show_on:e.target.value as StoreSettings['floating_wa_show_on']})}><option value="all">Semua Halaman</option><option value="home">Homepage Saja</option><option value="product">Halaman Produk Saja</option></select></div></div>
   <div className="twoCols"><div className="field"><label>Upload Icon/Image Custom</label><input className="input" type="file" accept="image/*" disabled={uploading==='wa'} onChange={e=>{const f=e.target.files?.[0];if(f)uploadAsset(f,'wa')}}/><small className="muted">{uploading==='wa'?'Sedang upload...':'Optional. Upload icon WA 3D atau maskot sendiri.'}</small></div><div className="field"><label>Custom Icon URL</label><input className="input" value={d.floating_wa_icon_url||''} onChange={e=>setD({...d,floating_wa_style:'custom',floating_wa_icon_url:e.target.value})} placeholder="https://..."/></div></div>
   {d.floating_wa_icon_url&&<img src={d.floating_wa_icon_url} alt="WA preview" style={{width:80,height:80,objectFit:'contain'}}/>}
  </div>

  <div className="field"><label>Jumlah Produk per Halaman Homepage</label><select className="input" value={d.home_products_per_page||8} onChange={e=>setD({...d,home_products_per_page:Number(e.target.value)})}><option value="6">6 produk</option><option value="8">8 produk</option><option value="10">10 produk</option><option value="12">12 produk</option><option value="16">16 produk</option><option value="20">20 produk</option></select><small className="muted">Homepage otomatis menampilkan pagination bila jumlah produk melebihi angka ini.</small></div>
  <div className="panel3d" style={{padding:20,marginTop:10}}><h2 style={{marginTop:0}}>PWA / Install App</h2><p className="muted">Aplikasi bisa di-install ke Home Screen. Nama dan icon PWA mengikuti pengaturan toko dan bisa di-upload sendiri.</p><div className="twoCols"><div className="field"><label>Nama Aplikasi</label><input className="input" value={d.pwa_name||''} onChange={e=>setD({...d,pwa_name:e.target.value})}/></div><div className="field"><label>Nama Pendek</label><input className="input" value={d.pwa_short_name||''} onChange={e=>setD({...d,pwa_short_name:e.target.value})}/></div></div><div className="twoCols"><div className="field"><label>Upload Icon PWA</label><input className="input" type="file" accept="image/png,image/webp,image/jpeg" disabled={uploading==='pwa'} onChange={e=>{const f=e.target.files?.[0];if(f)uploadAsset(f,'pwa')}}/><small className="muted">Rekomendasi 512×512 px, PNG/WebP, square.</small></div><div className="field"><label>Icon URL</label><input className="input" value={d.pwa_icon_url||''} onChange={e=>setD({...d,pwa_icon_url:e.target.value})} placeholder="https://..."/></div></div>{d.pwa_icon_url&&<img src={d.pwa_icon_url} alt="PWA icon" style={{width:90,height:90,objectFit:'cover',borderRadius:22}}/>}</div>
  <h2 style={{marginBottom:0,marginTop:10}}>Tema Warna</h2><p className="muted" style={{marginTop:0}}>Pilih satu dari 10 preset. Warna tetap bisa dikustom manual.</p><div className="themeGrid">{THEME_PRESETS.map(t=><button type="button" key={t.id} className={`themeSwatch ${d.theme_preset===t.id?'active':''}`} onClick={()=>pickTheme(t.id)}><div className="swatchBar" style={{background:`linear-gradient(135deg,${t.primary},${t.secondary},${t.accent})`}}/><strong>{t.name}</strong></button>)}</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:12}}>{[["Primary","primary_color"],["Secondary","secondary_color"],["Accent","accent_color"]].map(([label,key])=><div className="field" key={key}><label>{label}</label><div style={{display:'flex',gap:8}}><input style={{width:54,height:46,border:0,background:'transparent'}} type="color" value={(d as any)[key]} onChange={e=>setD({...d,[key]:e.target.value})}/><input className="input" value={(d as any)[key]} onChange={e=>setD({...d,[key]:e.target.value})}/></div></div>)}</div>
  <div className="glass" style={{padding:20,borderRadius:22,background:`linear-gradient(135deg,${d.primary_color},${d.secondary_color},${d.accent_color})`,color:'#fff'}}><strong>Live Preview</strong><div style={{fontSize:28,fontWeight:1000,marginTop:8}}>{d.brand_name}</div><div>{d.hero_title}</div></div>
  <button className="btn">Simpan Pengaturan</button>
 </form>
 <div className="glass" style={{padding:22,borderRadius:24,maxWidth:980,marginTop:20}}><h2>Ganti Password Owner</h2><div className="actions"><input className="input" type="password" value={pwd} onChange={e=>setPwd(e.target.value)} placeholder="Password baru minimal 6 karakter"/><button className="btn" onClick={changePass}>Ganti Password</button></div></div>{msg&&<div className="notice" style={{maxWidth:980,marginTop:14}}>{msg}</div>}</>
}
