'use client';
import { FormEvent, useEffect, useState } from 'react';
import AdminShell from '@/components/AdminShell';
import { createClient } from '@/lib/supabase';
import { StoreSettings } from '@/lib/types';
import { THEME_PRESETS } from '@/lib/themes';
const base:StoreSettings={id:1,brand_name:'ADCStore',tagline:'Digital Store & Affiliate Website for ADC Members',logo_url:null,whatsapp:null,instagram_url:null,primary_color:'#8b5cf6',secondary_color:'#c4b5fd',accent_color:'#f9a8d4',theme_preset:'lavender',hero_title:'Produk Digital Siap Jual untuk Member ADC',hero_subtitle:'Temukan produk digital pilihan dan beli melalui link affiliate resmi.',footer_text:'ADCStore'};
export default function Settings(){
 const [d,setD]=useState(base);const [msg,setMsg]=useState('');const [pwd,setPwd]=useState('');
 useEffect(()=>{createClient().from('store_settings').select('*').eq('id',1).maybeSingle().then(({data})=>{if(data)setD({...base,...data} as StoreSettings)})},[]);
 function pickTheme(id:string){const t=THEME_PRESETS.find(x=>x.id===id)!;setD({...d,theme_preset:id,primary_color:t.primary,secondary_color:t.secondary,accent_color:t.accent})}
 async function save(e:FormEvent){e.preventDefault();const {error}=await createClient().from('store_settings').upsert(d);setMsg(error?error.message:'Pengaturan dan tema berhasil disimpan.')}
 async function changePass(){if(pwd.length<6){setMsg('Password minimal 6 karakter.');return}const {error}=await createClient().auth.updateUser({password:pwd});setMsg(error?error.message:'Password owner berhasil diganti.');if(!error)setPwd('')}
 return <AdminShell><div className="topline"><div><h1>Pengaturan Toko</h1><p className="muted">Branding, homepage, dan tema warna global ADCStore.</p></div></div><form className="form glass" onSubmit={save} style={{padding:24,borderRadius:26,maxWidth:900}}><h2 style={{marginBottom:0}}>Branding</h2>{[['Nama Brand','brand_name'],['Tagline','tagline'],['Logo URL','logo_url'],['WhatsApp','whatsapp'],['Instagram URL','instagram_url'],['Hero Title','hero_title'],['Hero Subtitle','hero_subtitle'],['Footer Text','footer_text']].map(([label,key])=><div className="field" key={key}><label>{label}</label><input className="input" value={(d as any)[key]||''} onChange={e=>setD({...d,[key]:e.target.value})}/></div>)}<h2 style={{marginBottom:0,marginTop:10}}>Tema Warna</h2><p className="muted" style={{marginTop:0}}>Pilih satu dari 10 preset. Warna tetap bisa dikustom manual.</p><div className="themeGrid">{THEME_PRESETS.map(t=><button type="button" key={t.id} className={`themeSwatch ${d.theme_preset===t.id?'active':''}`} onClick={()=>pickTheme(t.id)}><div className="swatchBar" style={{background:`linear-gradient(135deg,${t.primary},${t.secondary},${t.accent})`}}/><strong>{t.name}</strong></button>)}</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:12}}>{[['Primary','primary_color'],['Secondary','secondary_color'],['Accent','accent_color']].map(([label,key])=><div className="field" key={key}><label>{label}</label><div style={{display:'flex',gap:8}}><input style={{width:54,height:46,border:0,background:'transparent'}} type="color" value={(d as any)[key]} onChange={e=>setD({...d,[key]:e.target.value})}/><input className="input" value={(d as any)[key]} onChange={e=>setD({...d,[key]:e.target.value})}/></div></div>)}</div><div className="glass" style={{padding:20,borderRadius:22,background:`linear-gradient(135deg,${d.primary_color},${d.secondary_color},${d.accent_color})`,color:'#fff'}}><strong>Live Preview</strong><div style={{fontSize:28,fontWeight:1000,marginTop:8}}>{d.brand_name}</div><div>{d.hero_title}</div></div><button className="btn">Simpan Pengaturan</button></form><div className="glass" style={{padding:22,borderRadius:24,maxWidth:900,marginTop:20}}><h2>Ganti Password Owner</h2><div className="actions"><input className="input" type="password" value={pwd} onChange={e=>setPwd(e.target.value)} placeholder="Password baru minimal 6 karakter"/><button className="btn" onClick={changePass}>Ganti Password</button></div></div>{msg&&<div className="notice" style={{maxWidth:900,marginTop:14}}>{msg}</div>}</AdminShell>
}
