'use client';
import { FormEvent, useEffect, useState } from 'react';
import MediaPicker from '@/components/MediaPicker';
import { createClient } from '@/lib/supabase';
import { SocialLink, StoreSettings } from '@/lib/types';
import { THEME_PRESETS } from '@/lib/themes';

const base:StoreSettings={id:1,brand_name:'Digital Store',tagline:'Digital product store',logo_url:null,favicon_url:null,whatsapp:null,instagram_url:null,primary_color:'#8b5cf6',secondary_color:'#c4b5fd',accent_color:'#f9a8d4',theme_preset:'lavender',hero_badge:'BONUS EKSKLUSIF',hero_title:'Produk Digital Siap Jual untuk Member ADC',hero_subtitle:'Temukan produk digital pilihan dan beli melalui link affiliate resmi.',hero_primary_cta_text:'Lihat Produk',hero_member_cta_text:'Masuk Member',hero_member_cta_enabled:true,hero_trust_1:'Produk siap promosi',hero_trust_2:'Link affiliate sendiri',hero_trust_3:'Tema bisa diganti',hero_visual_mode:'default',hero_image_url:null,hero_image_position:'right',hero_image_fit:'contain',hero_image_alt:'Hero image',catalog_eyebrow:'KATALOG DIGITAL',catalog_title:'Produk pilihan untuk mulai jualan',catalog_subtitle:'Produk ADC sudah tersedia. Pemilik toko tinggal mengatur link affiliate masing-masing.',floating_wa_enabled:false,floating_wa_number:null,floating_wa_target_type:'number',floating_wa_target_url:null,floating_wa_mobile_mode:'above_nav',floating_wa_message:'Halo, saya butuh bantuan tentang produk ini.',floating_wa_position:'right',floating_wa_style:'3d',floating_wa_icon_url:null,floating_wa_tooltip:'Butuh bantuan? Chat WhatsApp',floating_wa_show_on:'all',footer_text:'Digital Store',home_products_per_page:8,pwa_name:'Digital Store',pwa_short_name:'Store',pwa_icon_url:null,member_login_label:'Member',member_login_heading:'Welcome Back!',member_login_description:'Masuk untuk membuka member area dan mengatur tema pribadi Anda.',member_signup_heading:'Buat Akun Member',member_signup_description:'Daftar untuk mengakses member area.',owner_login_label:'Owner',owner_login_heading:'Owner Login',owner_login_description:'Halaman privat pemilik toko.',admin_console_label:'Owner Console',meta_pixel_enabled:false,meta_pixel_id:null,tiktok_pixel_enabled:false,tiktok_pixel_id:null,ga4_enabled:false,ga4_measurement_id:null,gtm_enabled:false,gtm_container_id:null};

export default function Settings(){
 const [d,setD]=useState(base),[msg,setMsg]=useState(''),[pwd,setPwd]=useState(''),[saving,setSaving]=useState(false),[modal,setModal]=useState<{type:'success'|'error';text:string}|null>(null);
 const [socials,setSocials]=useState<SocialLink[]>([]),[socialSearch,setSocialSearch]=useState(''),[socialPlatform,setSocialPlatform]=useState('Semua'),[socialPage,setSocialPage]=useState(1),[socialPageSize,setSocialPageSize]=useState(10);
 const emptySocial={id:'',platform:'Instagram',label:'Instagram',url:'',icon_url:null as string|null,is_active:true,sort_order:0}; const [socialForm,setSocialForm]=useState({...emptySocial});
 useEffect(()=>{const s=createClient();Promise.all([s.from('store_settings').select('*').eq('id',1).maybeSingle(),s.from('social_links').select('*').order('sort_order').order('created_at')]).then(([a,b])=>{if(a.data)setD({...base,...a.data} as StoreSettings);if(b.data)setSocials((b.data||[]) as SocialLink[])})},[]);
 function pickTheme(id:string){const t=THEME_PRESETS.find(x=>x.id===id)!;setD({...d,theme_preset:id,primary_color:t.primary,secondary_color:t.secondary,accent_color:t.accent})}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setMsg('');const payload={...d,id:1};const {error}=await createClient().from('store_settings').update(payload).eq('id',1);setSaving(false);if(error){setModal({type:'error',text:`Gagal menyimpan pengaturan: ${error.message}`});return}setModal({type:'success',text:'Pengaturan toko berhasil disimpan.'});}
 async function changePass(){if(pwd.length<6){setModal({type:'error',text:'Password minimal 6 karakter.'});return}const {error}=await createClient().auth.updateUser({password:pwd});if(error){setModal({type:'error',text:error.message});return}setPwd('');setModal({type:'success',text:'Password owner berhasil diganti.'})}

 async function reloadSocials(){const {data}=await createClient().from('social_links').select('*').order('sort_order').order('created_at');setSocials((data||[]) as SocialLink[])}
 async function saveSocial(){if(!socialForm.platform.trim()||!socialForm.url.trim()){setModal({type:'error',text:'Platform dan URL sosial media wajib diisi.'});return}const payload={platform:socialForm.platform.trim(),label:(socialForm.label||socialForm.platform).trim(),url:socialForm.url.trim(),icon_url:socialForm.icon_url||null,is_active:socialForm.is_active,sort_order:Number(socialForm.sort_order||0)};const s=createClient();const res=socialForm.id?await s.from('social_links').update(payload).eq('id',socialForm.id):await s.from('social_links').insert(payload);if(res.error){setModal({type:'error',text:res.error.message});return}setSocialForm({...emptySocial});await reloadSocials();setModal({type:'success',text:'Sosial media berhasil disimpan.'})}
 async function deleteSocial(id:string){const {error}=await createClient().from('social_links').delete().eq('id',id);if(error){setModal({type:'error',text:error.message});return}await reloadSocials();setSocialForm({...emptySocial});setModal({type:'success',text:'Sosial media berhasil dihapus.'})}
 return <><div className="topline"><div><h1>Pengaturan Toko</h1><p className="muted">Branding, homepage, login, favicon, WhatsApp melayang, PWA, dan tema warna toko.</p></div></div>
 <form className="form glass" onSubmit={save} style={{padding:24,borderRadius:26,maxWidth:980}}>
  <h2 style={{marginBottom:0}}>Branding</h2>
  <div className="twoCols"><div className="field"><MediaPicker currentUrls={d.logo_url?[d.logo_url]:[]} label="Logo Brand" onSelect={urls=>setD({...d,logo_url:urls[0]||null})}/><small className="muted">Logo transparan dipertahankan tanpa background tambahan.</small></div><div className="field"><label>Logo URL</label><input className="input" value={d.logo_url||''} onChange={e=>setD({...d,logo_url:e.target.value})} placeholder="https://..."/></div></div>
  {d.logo_url&&<img src={d.logo_url} alt="Logo preview" className="brandLogoTransparent" style={{maxWidth:180,maxHeight:80,objectFit:'contain',marginBottom:12}}/>}
  <div className="twoCols"><div className="field"><MediaPicker currentUrls={d.favicon_url?[d.favicon_url]:[]} label="Favicon" onSelect={urls=>setD({...d,favicon_url:urls[0]||null})}/><small className="muted">Rekomendasi square 64×64 atau 128×128. Jika kosong, otomatis pakai Logo Brand.</small></div><div className="field"><label>Favicon URL</label><input className="input" value={d.favicon_url||''} onChange={e=>setD({...d,favicon_url:e.target.value})} placeholder="https://..."/></div></div>
  {[['Nama Brand','brand_name'],['Tagline','tagline'],['WhatsApp Utama','whatsapp'],['Footer Text','footer_text']].map(([label,key])=><div className="field" key={key}><label>{label}</label><input className="input" value={(d as any)[key]||''} onChange={e=>setD({...d,[key]:e.target.value})}/></div>)}

  <div className="panel3d" style={{padding:20,marginTop:10}}><h2 style={{marginTop:0}}>Sosial Media</h2><p className="muted">Optional dan dinamis. Tambahkan sebanyak yang diperlukan. Jika kosong, sosial media tidak ditampilkan di storefront.</p>
   <div className="threeCols"><div className="field"><label>Platform</label><select className="input" value={socialForm.platform} onChange={e=>{const v=e.target.value;setSocialForm({...socialForm,platform:v,label:socialForm.label===socialForm.platform? v:socialForm.label})}}><option>Instagram</option><option>Facebook</option><option>TikTok</option><option>YouTube</option><option>Telegram</option><option>LinkedIn</option><option>X / Twitter</option><option>Website</option><option>Marketplace</option><option>Custom</option></select></div><div className="field"><label>Label</label><input className="input" value={socialForm.label} onChange={e=>setSocialForm({...socialForm,label:e.target.value})}/></div><div className="field"><label>Urutan</label><input className="input" type="number" value={socialForm.sort_order} onChange={e=>setSocialForm({...socialForm,sort_order:Number(e.target.value)})}/></div></div>
   <div className="field"><label>URL</label><input className="input" value={socialForm.url} onChange={e=>setSocialForm({...socialForm,url:e.target.value})} placeholder="https://..."/></div>
   <div className="twoCols"><div className="field"><MediaPicker currentUrls={socialForm.icon_url?[socialForm.icon_url]:[]} label="Icon Sosial Custom (Optional)" onSelect={urls=>setSocialForm({...socialForm,icon_url:urls[0]||null})}/><small className="muted">Pilih icon lama atau upload baru. Jika kosong, storefront memakai icon otomatis.</small></div><div className="field"><label>Icon URL (Optional)</label><input className="input" value={socialForm.icon_url||''} onChange={e=>setSocialForm({...socialForm,icon_url:e.target.value})} placeholder="https://..."/></div></div>
   <label className="toggleLine"><input type="checkbox" checked={socialForm.is_active} onChange={e=>setSocialForm({...socialForm,is_active:e.target.checked})}/> Aktif</label>
   <div className="actions"><button type="button" className="btn" onClick={saveSocial}>{socialForm.id?'Simpan Perubahan':'Tambah Sosial Media'}</button>{socialForm.id&&<button type="button" className="btn alt" onClick={()=>setSocialForm({...emptySocial})}>Batal Edit</button>}</div>
   <div className="filterBar" style={{marginTop:18}}><input className="input" value={socialSearch} onChange={e=>{setSocialSearch(e.target.value);setSocialPage(1)}} placeholder="Cari sosial media..."/><select className="input" value={socialPlatform} onChange={e=>{setSocialPlatform(e.target.value);setSocialPage(1)}}><option>Semua</option>{Array.from(new Set(socials.map(x=>x.platform))).map(x=><option key={x}>{x}</option>)}</select><select className="input" value={socialPageSize} onChange={e=>{setSocialPageSize(Number(e.target.value));setSocialPage(1)}}><option value="10">10 / halaman</option><option value="20">20 / halaman</option><option value="50">50 / halaman</option></select></div>
   {(()=>{const f=socials.filter(x=>(socialPlatform==='Semua'||x.platform===socialPlatform)&&`${x.platform} ${x.label} ${x.url}`.toLowerCase().includes(socialSearch.toLowerCase()));const pages=Math.max(1,Math.ceil(f.length/socialPageSize));const p=Math.min(socialPage,pages);const rows=f.slice((p-1)*socialPageSize,p*socialPageSize);return <><div className="socialAdminList">{rows.map(x=><div className="socialAdminRow" key={x.id}><strong>{x.platform}</strong><span>{x.label}</span><a href={x.url} target="_blank" rel="noreferrer" className="muted" style={{overflow:'hidden',textOverflow:'ellipsis'}}>{x.url}</a><div className="actions"><button type="button" className="btn alt" onClick={()=>setSocialForm({...x})}>Edit</button><button type="button" className="btn alt" onClick={()=>deleteSocial(x.id)}>Hapus</button></div></div>)}{rows.length===0&&<div className="notice">Belum ada sosial media.</div>}</div><div className="pager3d" style={{marginTop:12}}><span>{f.length} data • Halaman {p}/{pages}</span><div className="actions"><button type="button" className="btn alt" disabled={p<=1} onClick={()=>setSocialPage(v=>Math.max(1,v-1))}>←</button><button type="button" className="btn alt" disabled={p>=pages} onClick={()=>setSocialPage(v=>Math.min(pages,v+1))}>→</button></div></div></>})()}
  </div>

  <div className="panel3d" style={{padding:20,marginTop:10}}><h2 style={{marginTop:0}}>Tracking & Analytics</h2><p className="muted">Semua optional. Internal Analytics ADCStore tetap jalan walaupun provider iklan OFF.</p>
   <div className="twoCols"><label className="toggleLine"><input type="checkbox" checked={!!d.meta_pixel_enabled} onChange={e=>setD({...d,meta_pixel_enabled:e.target.checked})}/> Meta / Facebook Pixel</label><div className="field"><label>Meta Pixel ID</label><input className="input" value={d.meta_pixel_id||''} onChange={e=>setD({...d,meta_pixel_id:e.target.value})} placeholder="1234567890"/></div></div>
   <div className="twoCols"><label className="toggleLine"><input type="checkbox" checked={!!d.tiktok_pixel_enabled} onChange={e=>setD({...d,tiktok_pixel_enabled:e.target.checked})}/> TikTok Pixel</label><div className="field"><label>TikTok Pixel ID</label><input className="input" value={d.tiktok_pixel_id||''} onChange={e=>setD({...d,tiktok_pixel_id:e.target.value})} placeholder="CXXXXXXXX"/></div></div>
   <div className="twoCols"><label className="toggleLine"><input type="checkbox" checked={!!d.ga4_enabled} onChange={e=>setD({...d,ga4_enabled:e.target.checked})}/> Google Analytics 4</label><div className="field"><label>GA4 Measurement ID</label><input className="input" value={d.ga4_measurement_id||''} onChange={e=>setD({...d,ga4_measurement_id:e.target.value})} placeholder="G-XXXXXXXXXX"/></div></div>
   <div className="twoCols"><label className="toggleLine"><input type="checkbox" checked={!!d.gtm_enabled} onChange={e=>setD({...d,gtm_enabled:e.target.checked})}/> Google Tag Manager</label><div className="field"><label>GTM Container ID</label><input className="input" value={d.gtm_container_id||''} onChange={e=>setD({...d,gtm_container_id:e.target.value})} placeholder="GTM-XXXXXXX"/></div></div>
  </div>

  <div className="panel3d" style={{padding:20,marginTop:10}}><h2 style={{marginTop:0}}>Login & Area Brand</h2><p className="muted">Semua label login mengikuti brand dan bisa diedit. Logo memakai Logo Brand di atas.</p>
   <div className="field"><label>Label Login Member</label><input className="input" value={d.member_login_label||''} onChange={e=>setD({...d,member_login_label:e.target.value})} placeholder="Member"/></div>
   <div className="twoCols"><div className="field"><label>Heading Login Member</label><input className="input" value={d.member_login_heading||''} onChange={e=>setD({...d,member_login_heading:e.target.value})}/></div><div className="field"><label>Heading Daftar Member</label><input className="input" value={d.member_signup_heading||''} onChange={e=>setD({...d,member_signup_heading:e.target.value})}/></div></div>
   <div className="twoCols"><div className="field"><label>Deskripsi Login Member</label><textarea className="input" rows={2} value={d.member_login_description||''} onChange={e=>setD({...d,member_login_description:e.target.value})}/></div><div className="field"><label>Deskripsi Daftar Member</label><textarea className="input" rows={2} value={d.member_signup_description||''} onChange={e=>setD({...d,member_signup_description:e.target.value})}/></div></div>
   <div className="twoCols"><div className="field"><label>Label Owner</label><input className="input" value={d.owner_login_label||''} onChange={e=>setD({...d,owner_login_label:e.target.value})}/></div><div className="field"><label>Label Dashboard Owner</label><input className="input" value={d.admin_console_label||''} onChange={e=>setD({...d,admin_console_label:e.target.value})}/></div></div>
   <div className="field"><label>Heading Login Owner</label><input className="input" value={d.owner_login_heading||''} onChange={e=>setD({...d,owner_login_heading:e.target.value})}/></div>
   <div className="field"><label>Deskripsi Login Owner</label><textarea className="input" rows={2} value={d.owner_login_description||''} onChange={e=>setD({...d,owner_login_description:e.target.value})}/></div>
  </div>

  <div className="panel3d" style={{padding:20,marginTop:10}}><h2 style={{marginTop:0}}>Homepage / Hero</h2><p className="muted">Semua teks di area hero dan katalog bisa diganti. Tidak hardcode lagi.</p>
   {[["Badge Hero","hero_badge"],["Hero Title","hero_title"],["Hero Subtitle","hero_subtitle"],["Teks CTA Utama","hero_primary_cta_text"],["Teks CTA Member","hero_member_cta_text"],["Highlight 1","hero_trust_1"],["Highlight 2","hero_trust_2"],["Highlight 3","hero_trust_3"],["Katalog Eyebrow","catalog_eyebrow"],["Judul Katalog","catalog_title"],["Subjudul Katalog","catalog_subtitle"]].map(([label,key])=><div className="field" key={key}><label>{label}</label><input className="input" value={(d as any)[key]||''} onChange={e=>setD({...d,[key]:e.target.value})}/></div>)}
   <label className="toggleLine"><input type="checkbox" checked={d.hero_member_cta_enabled} onChange={e=>setD({...d,hero_member_cta_enabled:e.target.checked})}/> Tampilkan tombol Masuk Member di hero</label>
   <div className="threeCols"><div className="field"><label>Tipe Visual Hero</label><select className="input" value={d.hero_visual_mode} onChange={e=>setD({...d,hero_visual_mode:e.target.value as StoreSettings['hero_visual_mode']})}><option value="default">Default 3D Illustration</option><option value="upload">Upload Image</option><option value="url">Image URL</option><option value="none">Tanpa Image</option></select></div><div className="field"><label>Posisi Image</label><select className="input" value={d.hero_image_position} onChange={e=>setD({...d,hero_image_position:e.target.value as StoreSettings['hero_image_position']})}><option value="right">Kanan</option><option value="left">Kiri</option></select></div><div className="field"><label>Object Fit</label><select className="input" value={d.hero_image_fit} onChange={e=>setD({...d,hero_image_fit:e.target.value as StoreSettings['hero_image_fit']})}><option value="contain">Contain</option><option value="cover">Cover</option></select></div></div>
   <div className="twoCols"><div className="field"><MediaPicker currentUrls={d.hero_image_url?[d.hero_image_url]:[]} label="Hero Image" onSelect={urls=>setD({...d,hero_visual_mode:'upload',hero_image_url:urls[0]||null})}/><small className="muted">Pilih aset lama atau upload baru.</small></div><div className="field"><label>Hero Image URL</label><input className="input" value={d.hero_image_url||''} onChange={e=>setD({...d,hero_visual_mode:'url',hero_image_url:e.target.value})} placeholder="https://..."/></div></div>
   <div className="field"><label>Hero Image Alt Text</label><input className="input" value={d.hero_image_alt||''} onChange={e=>setD({...d,hero_image_alt:e.target.value})}/></div>
   {d.hero_image_url&&<div className="glass" style={{padding:14,borderRadius:18}}><img src={d.hero_image_url} alt="Hero preview" style={{maxWidth:360,width:'100%',maxHeight:220,objectFit:'contain',borderRadius:16}}/></div>}
  </div>

  <div className="panel3d" style={{padding:20,marginTop:10}}><h2 style={{marginTop:0}}>Floating WhatsApp</h2><p className="muted">Optional. Pengunjung bisa klik tombol WhatsApp melayang jika butuh bantuan.</p>
   <label className="toggleLine"><input type="checkbox" checked={d.floating_wa_enabled} onChange={e=>setD({...d,floating_wa_enabled:e.target.checked})}/> Aktifkan Floating WhatsApp</label>
   <div className="twoCols"><div className="field"><label>Target WhatsApp</label><select className="input" value={d.floating_wa_target_type||'number'} onChange={e=>setD({...d,floating_wa_target_type:e.target.value as 'number'|'url'})}><option value="number">Nomor WhatsApp</option><option value="url">URL Langsung (Group / Channel / Community)</option></select></div><div className="field"><label>Tampilan di Mobile</label><select className="input" value={d.floating_wa_mobile_mode||'above_nav'} onChange={e=>setD({...d,floating_wa_mobile_mode:e.target.value as 'above_nav'|'nav_item'})}><option value="above_nav">Melayang di atas Bottom Navbar</option><option value="nav_item">Masuk ke Bottom Navbar</option></select></div></div>
   {d.floating_wa_target_type==='url'?<div className="field"><label>URL Tujuan WhatsApp</label><input className="input" value={d.floating_wa_target_url||''} onChange={e=>setD({...d,floating_wa_target_url:e.target.value})} placeholder="https://chat.whatsapp.com/... atau https://whatsapp.com/channel/..."/><small className="muted">Bisa Group, Channel, Community, atau URL WhatsApp lain.</small></div>:<><div className="field"><label>Nomor WhatsApp</label><input className="input" value={d.floating_wa_number||''} onChange={e=>setD({...d,floating_wa_number:e.target.value})} placeholder="62812..."/></div><div className="field"><label>Pesan Default</label><textarea className="input" rows={3} value={d.floating_wa_message||''} onChange={e=>setD({...d,floating_wa_message:e.target.value})}/></div></>}
   <div className="field"><label>Tooltip</label><input className="input" value={d.floating_wa_tooltip||''} onChange={e=>setD({...d,floating_wa_tooltip:e.target.value})} placeholder="Butuh bantuan? Chat WhatsApp"/></div>
   <div className="threeCols"><div className="field"><label>Posisi</label><select className="input" value={d.floating_wa_position} onChange={e=>setD({...d,floating_wa_position:e.target.value as StoreSettings['floating_wa_position']})}><option value="right">Kanan Bawah</option><option value="left">Kiri Bawah</option></select></div><div className="field"><label>Style</label><select className="input" value={d.floating_wa_style} onChange={e=>setD({...d,floating_wa_style:e.target.value as StoreSettings['floating_wa_style']})}><option value="3d">3D</option><option value="round">Bulat</option><option value="custom">Custom Image</option></select></div><div className="field"><label>Tampilkan di</label><select className="input" value={d.floating_wa_show_on} onChange={e=>setD({...d,floating_wa_show_on:e.target.value as StoreSettings['floating_wa_show_on']})}><option value="all">Semua Halaman</option><option value="home">Homepage Saja</option><option value="product">Halaman Produk Saja</option></select></div></div>
   <div className="twoCols"><div className="field"><MediaPicker currentUrls={d.floating_wa_icon_url?[d.floating_wa_icon_url]:[]} label="Icon/Image Floating WhatsApp" onSelect={urls=>setD({...d,floating_wa_style:'custom',floating_wa_icon_url:urls[0]||null})}/><small className="muted">Optional. Bisa pilih icon 3D/maskot yang pernah diupload.</small></div><div className="field"><label>Custom Icon URL</label><input className="input" value={d.floating_wa_icon_url||''} onChange={e=>setD({...d,floating_wa_style:'custom',floating_wa_icon_url:e.target.value})} placeholder="https://..."/></div></div>
   {d.floating_wa_icon_url&&<img src={d.floating_wa_icon_url} alt="WA preview" style={{width:80,height:80,objectFit:'contain'}}/>}
  </div>

  <div className="field"><label>Jumlah Produk per Halaman Homepage</label><select className="input" value={d.home_products_per_page||8} onChange={e=>setD({...d,home_products_per_page:Number(e.target.value)})}><option value="6">6 produk</option><option value="8">8 produk</option><option value="10">10 produk</option><option value="12">12 produk</option><option value="16">16 produk</option><option value="20">20 produk</option></select><small className="muted">Homepage otomatis menampilkan pagination bila jumlah produk melebihi angka ini.</small></div>
  <div className="panel3d" style={{padding:20,marginTop:10}}><h2 style={{marginTop:0}}>PWA / Install App</h2><p className="muted">Aplikasi bisa di-install ke Home Screen. Nama dan icon PWA mengikuti pengaturan toko dan bisa di-upload sendiri.</p><div className="twoCols"><div className="field"><label>Nama Aplikasi</label><input className="input" value={d.pwa_name||''} onChange={e=>setD({...d,pwa_name:e.target.value})}/></div><div className="field"><label>Nama Pendek</label><input className="input" value={d.pwa_short_name||''} onChange={e=>setD({...d,pwa_short_name:e.target.value})}/></div></div><div className="twoCols"><div className="field"><MediaPicker currentUrls={d.pwa_icon_url?[d.pwa_icon_url]:[]} label="Icon PWA" onSelect={urls=>setD({...d,pwa_icon_url:urls[0]||null})}/><small className="muted">Rekomendasi 512×512 px, PNG/WebP, square.</small></div><div className="field"><label>Icon URL</label><input className="input" value={d.pwa_icon_url||''} onChange={e=>setD({...d,pwa_icon_url:e.target.value})} placeholder="https://..."/></div></div>{d.pwa_icon_url&&<div className="pwaIconPreviewWrap"><img src={d.pwa_icon_url} alt="PWA icon preview" className="pwaIconPreview"/><div><strong>Preview Icon PWA</strong><div className="muted">Preview dikunci 96×96 agar resolusi asli file tidak membuat gambar membesar di halaman Settings.</div></div></div>}</div>
  <h2 style={{marginBottom:0,marginTop:10}}>Tema Warna</h2><p className="muted" style={{marginTop:0}}>Pilih satu dari 10 preset. Warna tetap bisa dikustom manual.</p><div className="themeGrid">{THEME_PRESETS.map(t=><button type="button" key={t.id} className={`themeSwatch ${d.theme_preset===t.id?'active':''}`} onClick={()=>pickTheme(t.id)}><div className="swatchBar" style={{background:`linear-gradient(135deg,${t.primary},${t.secondary},${t.accent})`}}/><strong>{t.name}</strong></button>)}</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:12}}>{[["Primary","primary_color"],["Secondary","secondary_color"],["Accent","accent_color"]].map(([label,key])=><div className="field" key={key}><label>{label}</label><div style={{display:'flex',gap:8}}><input style={{width:54,height:46,border:0,background:'transparent'}} type="color" value={(d as any)[key]} onChange={e=>setD({...d,[key]:e.target.value})}/><input className="input" value={(d as any)[key]} onChange={e=>setD({...d,[key]:e.target.value})}/></div></div>)}</div>
  <div className="glass" style={{padding:20,borderRadius:22,background:`linear-gradient(135deg,${d.primary_color},${d.secondary_color},${d.accent_color})`,color:'#fff'}}><strong>Live Preview</strong><div style={{fontSize:28,fontWeight:1000,marginTop:8}}>{d.brand_name}</div><div>{d.hero_title}</div></div>
  <button className="btn" type="submit" disabled={saving}>{saving?'Menyimpan...':'Simpan Pengaturan'}</button>
 </form>
 <div className="glass" style={{padding:22,borderRadius:24,maxWidth:980,marginTop:20}}><h2>Ganti Password Owner</h2><div className="actions"><input className="input" type="password" value={pwd} onChange={e=>setPwd(e.target.value)} placeholder="Password baru minimal 6 karakter"/><button className="btn" onClick={changePass}>Ganti Password</button></div></div>{msg&&<div className="notice" style={{maxWidth:980,marginTop:14}}>{msg}</div>} {modal&&<div className="modalBack" onClick={()=>setModal(null)}><div className="saveResultModal" onClick={e=>e.stopPropagation()}><div className={`saveResultIcon ${modal.type}`}>{modal.type==='success'?'✓':'!'}</div><h3>{modal.type==='success'?'Berhasil Disimpan':'Tidak Bisa Disimpan'}</h3><p>{modal.text}</p><button className="btn" type="button" onClick={()=>setModal(null)}>Tutup</button></div></div>}
</>
}
