'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase';
import { Profile, StoreSettings } from '@/lib/types';
import { THEME_PRESETS, getTheme, themeVars } from '@/lib/themes';
export default function Member(){const router=useRouter();const [p,setP]=useState<Profile|null>(null);const [email,setEmail]=useState('');const [loading,setLoading]=useState(true);const [msg,setMsg]=useState('');const [settings,setSettings]=useState<Partial<StoreSettings>>({});
 useEffect(()=>{const s=createClient();s.auth.getUser().then(async({data})=>{if(!data.user){router.replace('/member/login');return}const {data:admin}=await s.rpc('is_admin');if(admin){router.replace('/admin');return}setEmail(data.user.email||'');const {data:profile}=await s.from('profiles').select('*').eq('id',data.user.id).maybeSingle();setP(profile as Profile);const {data:store}=await s.from('store_settings').select('brand_name,logo_url').eq('id',1).maybeSingle();if(store)setSettings(store);setLoading(false)})},[router]);
 async function saveTheme(id:string){if(!p)return;const t=THEME_PRESETS.find(x=>x.id===id)!;const n={...p,theme_preset:id,custom_primary:t.primary,custom_secondary:t.secondary,custom_accent:t.accent};setP(n);const {error}=await createClient().from('profiles').update({theme_preset:id,custom_primary:t.primary,custom_secondary:t.secondary,custom_accent:t.accent}).eq('id',p.id);setMsg(error?error.message:'Tema pribadi tersimpan.')}
 async function logout(){await createClient().auth.signOut();router.replace('/member/login')}
 if(loading||!p)return <div style={{padding:40}}>Memuat member area...</div>;const base=getTheme(p.theme_preset);
 return <div className="themeRoot memberWrap" style={themeVars(base,{primary:p.custom_primary,secondary:p.custom_secondary,accent:p.custom_accent})}><div className="container memberGrid"><aside className="memberSide glass"><div className="brand" style={{marginBottom:20}}>{settings.logo_url?<img src={settings.logo_url} alt={settings.brand_name||'Brand'} className="brandLogoTransparent" style={{maxWidth:42,maxHeight:42,objectFit:'contain'}}/>:<span className="logo">{(settings.brand_name||'Digital Store').trim().charAt(0).toUpperCase()}</span>}<span>{settings.brand_name||'Digital Store'}</span></div><Link href="/member">Dashboard</Link><Link href="/member/access">Akses Produk</Link><Link href="/#produk">Katalog Produk</Link><a href="#tema">Tema Saya</a><button className="btn alt" style={{width:'100%',marginTop:14}} onClick={logout}>Keluar</button></aside><main className="memberMain glass"><span className="badge">MEMBER AREA</span><h1 style={{fontSize:42,marginBottom:4}}>Halo, {p.full_name||'Member'} 👋</h1><p className="muted">{email}</p><div className="statGrid" style={{marginTop:24}}><div className="statCard glass"><div className="statIcon">🛍️</div><h3>Katalog Produk</h3><p className="muted">Jelajahi produk digital di toko ini.</p></div><Link href="/member/access" className="statCard glass"><div className="statIcon">🔑</div><h3>Akses Produk</h3><p className="muted">Buka produk yang sudah diverifikasi.</p></Link><div className="statCard glass"><div className="statIcon">🎨</div><h3>Tema Pribadi</h3><p className="muted">Pilih tampilan favorit member area.</p></div></div><section id="tema" style={{marginTop:34}}><span className="eyebrow">PERSONALISASI</span><h2>Pilih tema member area</h2><div className="themeGrid">{THEME_PRESETS.map(t=><button key={t.id} className={`themeSwatch ${p.theme_preset===t.id?'active':''}`} onClick={()=>saveTheme(t.id)}><div className="swatchBar" style={{background:`linear-gradient(135deg,${t.primary},${t.secondary},${t.accent})`}}/><strong>{t.name}</strong></button>)}</div>{msg&&<div className="notice" style={{marginTop:14}}>{msg}</div>}</section></main></div></div>}
