'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { createClient } from '@/lib/supabase';
import { PaymentSettings, Product, StoreSettings } from '@/lib/types';
import { rupiah } from '@/lib/money';
import ThemeProvider from '@/components/ThemeProvider';
import { Building2, WalletCards, QrCode, CheckCircle2 } from 'lucide-react';
const fallback:StoreSettings={id:1,brand_name:'ADCStore',tagline:'Digital Store & Affiliate Website for ADC Members',logo_url:null,whatsapp:null,instagram_url:null,primary_color:'#8b5cf6',secondary_color:'#c4b5fd',accent_color:'#f9a8d4',theme_preset:'lavender',hero_title:'Produk Digital Siap Jual untuk Member ADC',hero_subtitle:'',footer_text:'ADCStore',home_products_per_page:8};
const payBase:PaymentSettings={id:1,banks:[],ewallets:[],qris_enabled:false,qris_label:'QRIS',qris_image_url:null,instructions:''};
export default function Checkout(){
 const {slug}=useParams<{slug:string}>(); const [p,setP]=useState<Product|null>(null); const [s,setS]=useState(fallback); const [pay,setPay]=useState(payBase); const [method,setMethod]=useState(''); const [form,setForm]=useState({name:'',email:'',wa:''}); const [done,setDone]=useState(''); const [msg,setMsg]=useState('');
 useEffect(()=>{const c=createClient();Promise.all([c.from('products').select('*').eq('slug',slug).maybeSingle(),c.from('store_settings').select('*').eq('id',1).maybeSingle(),c.from('payment_settings').select('*').eq('id',1).maybeSingle()]).then(([a,b,d])=>{setP(a.data as Product|null);if(b.data)setS({...fallback,...b.data} as StoreSettings);if(d.data){const x={...payBase,...d.data,banks:d.data.banks||[],ewallets:d.data.ewallets||[]} as PaymentSettings;setPay(x);const first=x.banks.find(v=>v.enabled);const w=x.ewallets.find(v=>v.enabled);setMethod(first?`bank:${first.id}`:w?`wallet:${w.id}`:x.qris_enabled?'qris':'')}})},[slug]);
 async function submit(e:FormEvent){e.preventDefault();if(!p||!method)return setMsg('Pilih metode pembayaran dulu.');const order=`ADC-${Date.now().toString().slice(-8)}`;const {error}=await createClient().from('orders').insert({order_number:order,product_id:p.id,customer_name:form.name,customer_email:form.email,customer_whatsapp:form.wa,amount:p.price,payment_method:method,status:'pending'});if(error)return setMsg(error.message);setDone(order)}
 if(!p)return <div style={{padding:50}}>Memuat checkout...</div>;
 const bank=pay.banks.find(x=>method===`bank:${x.id}`);const wallet=pay.ewallets.find(x=>method===`wallet:${x.id}`);
 return <ThemeProvider preset={s.theme_preset} primary={s.primary_color} secondary={s.secondary_color} accent={s.accent_color}><main className="checkoutPage3d"><div className="checkoutShell3d"><section className="checkoutProduct3d"><span className="eyebrow">CHECKOUT INTERNAL</span><h1>{p.name}</h1><p>{p.short_description}</p><div className="checkoutPrice">{rupiah(p.price)}</div><div className="miniOrderArt">ADC</div><Link href={`/product/${p.slug}`} className="btn soft">← Kembali ke Produk</Link></section><section className="checkoutForm3d">{done?<div className="success3d"><CheckCircle2 size={64}/><h2>Pesanan berhasil dibuat</h2><p>Nomor order Anda:</p><strong>{done}</strong><p className="muted">Lakukan pembayaran sesuai metode yang dipilih. Owner akan memverifikasi pembayaran Anda.</p><Link href="/member/login" className="btn">Masuk Member Area</Link></div>:<form className="form" onSubmit={submit}><h2>Data Pembeli</h2><div className="field"><label>Nama</label><input className="input" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="twoCols"><div className="field"><label>Email</label><input className="input" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div className="field"><label>WhatsApp</label><input className="input" required value={form.wa} onChange={e=>setForm({...form,wa:e.target.value})}/></div></div><h2>Pilih Pembayaran</h2><div className="checkoutMethods">{pay.banks.filter(x=>x.enabled).map(x=><button type="button" key={x.id} onClick={()=>setMethod(`bank:${x.id}`)} className={method===`bank:${x.id}`?'active':''}><Building2/><span><b>{x.bank}</b><small>Transfer Bank</small></span></button>)}{pay.ewallets.filter(x=>x.enabled).map(x=><button type="button" key={x.id} onClick={()=>setMethod(`wallet:${x.id}`)} className={method===`wallet:${x.id}`?'active':''}><WalletCards/><span><b>{x.provider}</b><small>E-Wallet</small></span></button>)}{pay.qris_enabled&&<button type="button" onClick={()=>setMethod('qris')} className={method==='qris'?'active':''}><QrCode/><span><b>{pay.qris_label}</b><small>QRIS Statis</small></span></button>}</div>{bank&&<div className="payDetail3d"><b>{bank.bank}</b><strong>{bank.account_number}</strong><span>a.n. {bank.account_name}</span></div>}{wallet&&<div className="payDetail3d"><b>{wallet.provider}</b><strong>{wallet.number}</strong><span>a.n. {wallet.account_name}</span></div>}{method==='qris'&&pay.qris_image_url&&<div className="qrisCheckout3d"><img src={pay.qris_image_url} alt="QRIS"/></div>}<div className="notice">{pay.instructions}</div>{msg&&<div className="notice">{msg}</div>}<button className="btn full">Buat Pesanan • {rupiah(p.price)}</button></form>}</section></div></main></ThemeProvider>
}
