'use client';
import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase';
import ThreeDArt from '@/components/ThreeDArt';
export default function MemberLogin(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [name,setName]=useState('');const [mode,setMode]=useState<'login'|'signup'>('login');const [msg,setMsg]=useState('');const router=useRouter();
 async function submit(e:FormEvent){e.preventDefault();setMsg('Memproses...');const s=createClient();if(mode==='login'){const {data,error}=await s.auth.signInWithPassword({email,password});if(error)return setMsg(error.message);const {data:admin}=await s.rpc('is_admin');if(admin){await s.auth.signOut();return setMsg('Akun owner/admin harus masuk melalui halaman owner.')}router.replace('/member')}else{const {error}=await s.auth.signUp({email,password,options:{data:{full_name:name}}});setMsg(error?error.message:'Pendaftaran berhasil. Cek email bila konfirmasi email aktif, lalu login sebagai member.')}}
 return <div className="themeRoot authPage"><div className="authCard glass"><div className="authArt"><ThreeDArt/></div><div className="authForm"><div className="brand"><span className="logo">A</span><span>ADCStore Member</span></div><h1 style={{fontSize:42,marginBottom:8}}>{mode==='login'?'Welcome Back!':'Buat Akun Member'}</h1><p className="muted">{mode==='login'?'Masuk untuk membuka member area dan mengatur tema pribadi Anda.':'Daftar sebagai member ADCStore.'}</p><form className="form" onSubmit={submit}>{mode==='signup'&&<div className="field"><label>Nama</label><input className="input" value={name} onChange={e=>setName(e.target.value)} required/></div>}<div className="field"><label>Email</label><input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="field"><label>Password</label><input className="input" type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={6} required/></div><button className="btn">{mode==='login'?'Login Member':'Daftar Member'}</button>{msg&&<div className="notice">{msg}</div>}</form><button className="btn alt" style={{marginTop:12,width:'100%'}} onClick={()=>{setMode(mode==='login'?'signup':'login');setMsg('')}}>{mode==='login'?'Belum punya akun? Daftar':'Sudah punya akun? Login'}</button><div style={{marginTop:20,textAlign:'center'}}><Link className="muted" href="/">← Kembali ke toko</Link></div></div></div></div>}
