'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import AdminShell from '@/components/AdminShell';
import { createClient } from '@/lib/supabase';
import { Product } from '@/lib/types';
import { rupiah } from '@/lib/money';
import { FileCode2, Link2, PackagePlus, Pencil, Trash2, UploadCloud, X, Star, Video } from 'lucide-react';

type Draft=Omit<Product,'id'>;
const blank:Draft={name:'',slug:'',short_description:'',description:'',image_url:'',gallery_images:[],video_url:'',price:0,compare_at_price:0,show_discount_badge:true,discount_badge_text:'',category:'Produk Digital',affiliate_salespage_url:'',internal_salespage_html:'',affiliate_url:'',cta_text:'Beli di Official Website',internal_cta_text:'Checkout di Website',affiliate_salespage_cta_text:'Lihat Salespage Official',sale_mode:'affiliate',featured:false,is_active:true,sort_order:0};
const slugify=(x:string)=>x.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
export default function Products(){
 const [rows,setRows]=useState<Product[]>([]),[q,setQ]=useState(''),[status,setStatus]=useState('all'),[category,setCategory]=useState('all'),[mode,setMode]=useState('all');
 const [page,setPage]=useState(1),[size,setSize]=useState(10),[edit,setEdit]=useState<Product|null>(null),[draft,setDraft]=useState<Draft>(blank),[show,setShow]=useState(false),[msg,setMsg]=useState(''),[uploading,setUploading]=useState(false),[galleryUrl,setGalleryUrl]=useState('');
 async function load(){const {data}=await createClient().from('products').select('*').order('sort_order');setRows(((data||[]) as Product[]).map(x=>({...x,gallery_images:x.gallery_images||[]})))} useEffect(()=>{load()},[]);
 const categories=useMemo(()=>Array.from(new Set(rows.map(x=>x.category).filter(Boolean) as string[])),[rows]);
 const filtered=useMemo(()=>rows.filter(r=>(status==='all'||(status==='active'&&r.is_active)||(status==='inactive'&&!r.is_active))&&(category==='all'||r.category===category)&&(mode==='all'||r.sale_mode===mode)&&`${r.name} ${r.category||''} ${r.slug}`.toLowerCase().includes(q.toLowerCase())),[rows,q,status,category,mode]);
 const pages=Math.max(1,Math.ceil(filtered.length/size)); const safePage=Math.min(page,pages); const view=filtered.slice((safePage-1)*size,safePage*size);
 function openNew(){setEdit(null);setDraft(blank);setGalleryUrl('');setShow(true);setMsg('')} function openEdit(p:Product){setEdit(p);setDraft({...blank,...p,gallery_images:p.gallery_images||[]});setGalleryUrl('');setShow(true);setMsg('')}
 async function uploadFiles(files:FileList|null){if(!files?.length)return;setUploading(true);setMsg('');const s=createClient();const urls:string[]=[];for(const file of Array.from(files)){const ext=file.name.split('.').pop()||'jpg';const path=`products/${crypto.randomUUID()}.${ext}`;const {error}=await s.storage.from('store-assets').upload(path,file,{upsert:false,contentType:file.type||undefined});if(error){setMsg(error.message);continue}urls.push(s.storage.from('store-assets').getPublicUrl(path).data.publicUrl)}setDraft(d=>({...d,image_url:d.image_url||urls[0]||'',gallery_images:[...d.gallery_images,...urls.filter(u=>u!==d.image_url)]}));setUploading(false)}
 function addGalleryUrl(){const u=galleryUrl.trim();if(!u)return;setDraft(d=>({...d,image_url:d.image_url||u,gallery_images:[...d.gallery_images,u]}));setGalleryUrl('')}
 function removeImage(url:string){setDraft(d=>{const gallery=d.gallery_images.filter(x=>x!==url);return {...d,gallery_images:gallery,image_url:d.image_url===url?(gallery[0]||''):d.image_url}})}
 function setCover(url:string){setDraft(d=>({...d,image_url:url,gallery_images:Array.from(new Set([url,...d.gallery_images]))}))}
 async function save(e:FormEvent){e.preventDefault();const s=createClient();const gallery=Array.from(new Set([draft.image_url,...draft.gallery_images].filter(Boolean) as string[]));const payload={...draft,gallery_images:gallery,slug:draft.slug||slugify(draft.name),price:Number(draft.price),compare_at_price:Number(draft.compare_at_price||0),sort_order:Number(draft.sort_order)};const res=edit?await s.from('products').update(payload).eq('id',edit.id):await s.from('products').insert(payload);if(res.error){setMsg(res.error.message);return}setShow(false);await load()}
 async function remove(id:string){if(!confirm('Hapus produk ini?'))return;await createClient().from('products').delete().eq('id',id);await load()}
 return <AdminShell><div className="pageHead3d"><div><span className="eyebrow">KATALOG ADC</span><h1>Produk ADC</h1><p>Atur galeri, video sales letter, salespage, checkout internal, dan link official affiliate.</p></div><button className="btn" onClick={openNew}><PackagePlus size={18}/> Tambah Produk</button></div>
 <div className="filterPanel3d"><input className="input" placeholder="Cari nama, slug, kategori..." value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/><select className="input" value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option value="all">Semua Kategori</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select className="input" value={mode} onChange={e=>{setMode(e.target.value);setPage(1)}}><option value="all">Semua Mode</option><option value="affiliate">Affiliate</option><option value="internal">Internal</option><option value="both">Both</option></select><select className="input" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="all">Semua Status</option><option value="active">Aktif</option><option value="inactive">Nonaktif</option></select><select className="input" value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}><option value="10">10 / halaman</option><option value="20">20 / halaman</option><option value="50">50 / halaman</option></select></div>
 <div className="productAdminCards">{view.map(p=><article className="productAdminCard" key={p.id}><div className="productAdminThumb">{p.image_url?<img src={p.image_url} alt={p.name}/>:<span>{p.name.slice(0,1)}</span>}</div><div className="productAdminInfo"><div className="adminCardTop"><div><span className="badge small">{p.category||'Produk Digital'}</span><h3>{p.name}</h3><small>/{p.slug}</small></div><span className={`statusPill ${p.is_active?'paid':'cancelled'}`}>{p.is_active?'Aktif':'Nonaktif'}</span></div><div className="productAdminMeta"><span><b>{rupiah(p.price)}</b><small>Harga Publish</small></span><span><b>{p.compare_at_price>p.price?rupiah(p.compare_at_price):'—'}</b><small>Harga Coret</small></span><span><b>{p.gallery_images?.length||0}</b><small>Gambar</small></span><span><b>{p.video_url?'Ada':'—'}</b><small>Video</small></span><span><b>{p.sale_mode}</b><small>Mode jual</small></span></div><div className="productAdminActions"><button className="btn alt" onClick={()=>openEdit(p)}><Pencil size={17}/> Edit</button><button className="btn alt dangerText" onClick={()=>remove(p.id)}><Trash2 size={17}/> Hapus</button></div></div></article>)}{!view.length&&<div className="empty3d panel3d">Belum ada produk.</div>}</div>
 <div className="pager3d"><span>{filtered.length} produk • Halaman {safePage}/{pages}</span><div className="actions"><button className="btn alt" disabled={safePage<=1} onClick={()=>setPage(x=>Math.max(1,x-1))}>←</button><button className="btn alt" disabled={safePage>=pages} onClick={()=>setPage(x=>Math.min(pages,x+1))}>→</button></div></div>
 {show&&<div className="modalBack" onMouseDown={()=>setShow(false)}><div className="modal3d" onMouseDown={e=>e.stopPropagation()}><div className="topline"><div><span className="eyebrow">PRODUK</span><h2>{edit?'Edit Produk':'Tambah Produk'}</h2></div><button className="iconBtn3d" onClick={()=>setShow(false)}>×</button></div><form className="form" onSubmit={save}>
 <div className="twoCols"><div className="field"><label>Nama Produk</label><input className="input" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value,slug:edit?draft.slug:slugify(e.target.value)})} required/></div><div className="field"><label>Slug</label><input className="input" value={draft.slug} onChange={e=>setDraft({...draft,slug:slugify(e.target.value)})}/></div></div><div className="field"><label>Deskripsi Singkat</label><input className="input" value={draft.short_description||''} onChange={e=>setDraft({...draft,short_description:e.target.value})}/></div><div className="field"><label>Deskripsi</label><textarea className="input" rows={5} value={draft.description||''} onChange={e=>setDraft({...draft,description:e.target.value})}/></div>
 <div className="panel3d" style={{padding:18}}><div className="inlineHead"><label><UploadCloud size={17}/> Galeri Produk</label><small className="muted">Upload banyak gambar sekaligus atau tambah URL satu per satu.</small></div><div className="twoCols"><div className="field"><label>Upload Images</label><input className="input" type="file" accept="image/*" multiple disabled={uploading} onChange={e=>uploadFiles(e.target.files)}/><small className="muted">{uploading?'Sedang upload...':'Bisa pilih beberapa JPG, PNG, WEBP sekaligus.'}</small></div><div className="field"><label>Tambah URL Image Address</label><div className="actions"><input className="input" value={galleryUrl} onChange={e=>setGalleryUrl(e.target.value)} placeholder="https://..."/><button className="btn alt" type="button" onClick={addGalleryUrl}>Tambah</button></div></div></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(130px,1fr))',gap:12,marginTop:12}}>{Array.from(new Set([draft.image_url,...draft.gallery_images].filter(Boolean) as string[])).map(url=><div key={url} style={{position:'relative'}}><img src={url} alt="Product" style={{width:'100%',height:100,objectFit:'cover',borderRadius:16,border:draft.image_url===url?'3px solid var(--primary)':'1px solid rgba(0,0,0,.08)'}}/><button type="button" title="Jadikan cover" onClick={()=>setCover(url)} style={{position:'absolute',left:6,bottom:6,border:0,borderRadius:10,padding:6,cursor:'pointer'}}><Star size={14} fill={draft.image_url===url?'currentColor':'none'}/></button><button type="button" title="Hapus gambar" onClick={()=>removeImage(url)} style={{position:'absolute',right:6,top:6,border:0,borderRadius:10,padding:6,cursor:'pointer'}}><X size={14}/></button></div>)}</div></div>
 <div className="panel3d" style={{padding:18}}><div className="inlineHead"><label><Video size={17}/> Video Sales Letter</label><small className="muted">YouTube, Vimeo, atau direct MP4/WebM URL.</small></div><div className="field"><label>URL Video</label><input className="input" value={draft.video_url||''} onChange={e=>setDraft({...draft,video_url:e.target.value})} placeholder="https://youtube.com/watch?v=..."/></div></div>
 <div className="threeCols"><div className="field"><label>Harga Normal / Coret</label><input className="input" type="number" min="0" value={draft.compare_at_price||0} onChange={e=>setDraft({...draft,compare_at_price:Number(e.target.value)})}/><small className="muted">Kosong / 0 = tidak tampil harga coret.</small></div><div className="field"><label>Harga Publish / Jual</label><input className="input" type="number" min="0" value={draft.price} onChange={e=>setDraft({...draft,price:Number(e.target.value)})}/></div><div className="field"><label>Kategori</label><input className="input" value={draft.category||''} onChange={e=>setDraft({...draft,category:e.target.value})}/></div></div><div className="threeCols"><div className="field"><label>Mode Penjualan</label><select className="input" value={draft.sale_mode} onChange={e=>setDraft({...draft,sale_mode:e.target.value as Draft['sale_mode']})}><option value="affiliate">Affiliate Only</option><option value="internal">Internal Checkout</option><option value="both">Both — Website + Official</option></select></div><label className="toggleLine"><input type="checkbox" checked={draft.show_discount_badge} onChange={e=>setDraft({...draft,show_discount_badge:e.target.checked})}/> Tampilkan badge diskon otomatis</label><div className="field"><label>Teks Badge Custom (optional)</label><input className="input" value={draft.discount_badge_text||''} onChange={e=>setDraft({...draft,discount_badge_text:e.target.value})} placeholder="PROMO SPESIAL"/></div></div>
 <div className="panel3d" style={{padding:18}}><div className="inlineHead"><label><FileCode2 size={17}/> Salespage</label><small className="muted">Keduanya optional.</small></div><div className="field"><label>Salespage Affiliate / Official</label><input className="input" value={draft.affiliate_salespage_url||''} onChange={e=>setDraft({...draft,affiliate_salespage_url:e.target.value})} placeholder="https://official.../salespage"/></div><div className="field"><label>Teks Tombol Salespage Official</label><input className="input" value={draft.affiliate_salespage_cta_text||''} onChange={e=>setDraft({...draft,affiliate_salespage_cta_text:e.target.value})}/></div><div className="field"><label>Salespage Internal — HTML Code</label><textarea className="input codeArea" rows={9} value={draft.internal_salespage_html||''} onChange={e=>setDraft({...draft,internal_salespage_html:e.target.value})} placeholder="<section>...</section>"/></div></div>
 <div className="panel3d" style={{padding:18}}><div className="inlineHead"><label><Link2 size={17}/> CTA Checkout</label><small className="muted">Website sendiri, official ADC, atau keduanya.</small></div>{draft.sale_mode!=='internal'&&<><div className="field"><label>Link Checkout Affiliate / Official</label><input className="input" value={draft.affiliate_url||''} onChange={e=>setDraft({...draft,affiliate_url:e.target.value})} placeholder="https://official.../checkout"/></div><div className="field"><label>Teks CTA Official</label><input className="input" value={draft.cta_text} onChange={e=>setDraft({...draft,cta_text:e.target.value})}/></div></>}{draft.sale_mode!=='affiliate'&&<div className="field"><label>Teks CTA Checkout Website</label><input className="input" value={draft.internal_cta_text} onChange={e=>setDraft({...draft,internal_cta_text:e.target.value})}/></div>}</div>
 <div className="field"><label>Urutan</label><input className="input" type="number" value={draft.sort_order} onChange={e=>setDraft({...draft,sort_order:Number(e.target.value)})}/></div><div className="toggleGroup"><label className="toggleLine"><input type="checkbox" checked={draft.is_active} onChange={e=>setDraft({...draft,is_active:e.target.checked})}/> Aktif</label><label className="toggleLine"><input type="checkbox" checked={draft.featured} onChange={e=>setDraft({...draft,featured:e.target.checked})}/> Featured</label></div>{msg&&<div className="notice">{msg}</div>}<button className="btn">Simpan Produk</button></form></div></div>}</AdminShell>
}
