'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import StoreNav from '@/components/StoreNav';
import ThreeDArt from '@/components/ThreeDArt';
import ThemeProvider from '@/components/ThemeProvider';
import { createClient } from '@/lib/supabase';
import { Product, StoreSettings } from '@/lib/types';
import { rupiah } from '@/lib/money';
const fallback:StoreSettings={id:1,brand_name:'ADCStore',tagline:'Digital Store & Affiliate Website for ADC Members',logo_url:null,whatsapp:null,instagram_url:null,primary_color:'#8b5cf6',secondary_color:'#c4b5fd',accent_color:'#f9a8d4',theme_preset:'lavender',hero_title:'Produk Digital Siap Jual untuk Member ADC',hero_subtitle:'Temukan produk digital pilihan, pelajari manfaatnya, lalu beli melalui link affiliate resmi.',footer_text:'ADCStore — Digital Store & Affiliate Website for ADC Members'};
export default function Home(){
 const [settings,setSettings]=useState<StoreSettings>(fallback); const [products,setProducts]=useState<Product[]>([]); const [q,setQ]=useState(''); const [cat,setCat]=useState('Semua');
 useEffect(()=>{const s=createClient();Promise.all([s.from('store_settings').select('*').eq('id',1).maybeSingle(),s.from('products').select('*').eq('is_active',true).order('sort_order')]).then(([a,b])=>{if(a.data)setSettings({...fallback,...a.data} as StoreSettings);if(b.data)setProducts(b.data as Product[])})},[]);
 const cats=['Semua',...Array.from(new Set(products.map(x=>x.category).filter(Boolean) as string[]))];
 const shown=useMemo(()=>products.filter(p=>(cat==='Semua'||p.category===cat)&&(`${p.name} ${p.short_description||''}`.toLowerCase().includes(q.toLowerCase()))),[products,q,cat]);
 return <ThemeProvider preset={settings.theme_preset} primary={settings.primary_color} secondary={settings.secondary_color} accent={settings.accent_color}><StoreNav brand={settings.brand_name}/><header className="hero"><div className="container heroGrid"><div className="heroCopy"><span className="badge">BONUS EKSKLUSIF • ADCStore</span><h1>{settings.hero_title}</h1><p>{settings.hero_subtitle}</p><div className="actions"><a href="#produk" className="btn">Lihat Produk</a><Link href="/member/login" className="btn soft">Masuk Member</Link></div><div className="trustRow"><span>✦ Produk siap promosi</span><span>✦ Link affiliate sendiri</span><span>✦ Tema bisa diganti</span></div></div><ThreeDArt/></div></header><section className="section" id="produk"><div className="container"><div className="sectionHead"><div><span className="eyebrow">KATALOG DIGITAL</span><h2>Produk pilihan untuk mulai jualan</h2><p className="muted">Produk ADC sudah tersedia. Pemilik toko tinggal mengatur link affiliate masing-masing.</p></div></div><div className="filterBar"><input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari produk..."/><select className="input" value={cat} onChange={e=>setCat(e.target.value)}>{cats.map(c=><option key={c}>{c}</option>)}</select></div><div className="grid productGrid">{shown.map((p,i)=><article className="card productCard" key={p.id}><div className="cardFloat">{i%3===0?'✦':i%3===1?'♥':'↗'}</div>{p.image_url?<img src={p.image_url} className="productImage" alt={p.name}/>:<div className="productImage placeholderArt"><span>ADC</span></div>}<div className="cardBody"><div className="badge small">{p.category||'Produk Digital'}</div><h3>{p.name}</h3><p className="muted">{p.short_description}</p><div className="price">{rupiah(p.price)}</div><Link className="btn full" href={`/product/${p.slug}`}>Lihat Detail</Link></div></article>)}{shown.length===0&&<div className="notice">Belum ada produk yang cocok.</div>}</div></div></section><footer className="footer"><div className="container">{settings.footer_text}</div></footer></ThemeProvider>
}
