'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import StoreNav from '@/components/StoreNav';
import ThreeDArt from '@/components/ThreeDArt';
import ThemeProvider from '@/components/ThemeProvider';
import { createClient } from '@/lib/supabase';
import { HomeBanner, Product, StoreSettings, SocialLink } from '@/lib/types';
import HomeBannerSlider from '@/components/HomeBannerSlider';
import { rupiah } from '@/lib/money';
const fallback:StoreSettings={id:1,brand_name:'Digital Store',tagline:'Digital product store',logo_url:null,whatsapp:null,instagram_url:null,primary_color:'#8b5cf6',secondary_color:'#c4b5fd',accent_color:'#f9a8d4',theme_preset:'lavender',hero_badge:'BONUS EKSKLUSIF',hero_title:'Produk Digital Siap Jual untuk Member ADC',hero_subtitle:'Temukan produk digital pilihan, pelajari manfaatnya, lalu beli melalui link affiliate resmi.',hero_primary_cta_text:'Lihat Produk',hero_member_cta_text:'Masuk Member',hero_member_cta_enabled:true,hero_trust_1:'Produk siap promosi',hero_trust_2:'Link affiliate sendiri',hero_trust_3:'Tema bisa diganti',hero_visual_mode:'default',hero_image_url:null,hero_image_position:'right',hero_image_fit:'contain',hero_image_alt:'Hero image',catalog_eyebrow:'KATALOG DIGITAL',catalog_title:'Produk pilihan untuk mulai jualan',catalog_subtitle:'Produk ADC sudah tersedia. Pemilik toko tinggal mengatur link affiliate masing-masing.',floating_wa_enabled:false,floating_wa_number:null,floating_wa_message:'Halo, saya butuh bantuan tentang produk ini.',floating_wa_position:'right',floating_wa_style:'3d',floating_wa_icon_url:null,floating_wa_tooltip:'Butuh bantuan? Chat WhatsApp',floating_wa_show_on:'all',footer_text:'Digital Store',home_products_per_page:8,pwa_name:'Digital Store',pwa_short_name:'Store',pwa_icon_url:null};
export default function Home(){
 const [settings,setSettings]=useState<StoreSettings>(fallback),[products,setProducts]=useState<Product[]>([]),[banners,setBanners]=useState<HomeBanner[]>([]),[socials,setSocials]=useState<SocialLink[]>([]),[q,setQ]=useState(''),[cat,setCat]=useState('Semua'),[page,setPage]=useState(1);
 useEffect(()=>{const s=createClient();Promise.all([s.from('store_settings').select('*').eq('id',1).maybeSingle(),s.from('products').select('*').eq('is_active',true).order('sort_order'),s.from('homepage_banners').select('*').eq('is_active',true).order('sort_order'),s.from('social_links').select('*').eq('is_active',true).order('sort_order')]).then(([a,b,c,d])=>{if(a.data)setSettings({...fallback,...a.data} as StoreSettings);if(b.data)setProducts(((b.data||[]) as Product[]).map(x=>({...x,gallery_images:x.gallery_images||[],compare_at_price:Number(x.compare_at_price||0),show_discount_badge:x.show_discount_badge!==false})));if(c.data)setBanners((c.data||[]) as HomeBanner[]);if(d.data)setSocials((d.data||[]) as SocialLink[])})},[]);
 const cats=['Semua',...Array.from(new Set(products.map(x=>x.category).filter(Boolean) as string[]))];
 const filtered=useMemo(()=>products.filter(p=>(cat==='Semua'||p.category===cat)&&(`${p.name} ${p.short_description||''} ${p.category||''}`.toLowerCase().includes(q.toLowerCase()))),[products,q,cat]);
 const size=settings.home_products_per_page||8,pages=Math.max(1,Math.ceil(filtered.length/size)),safePage=Math.min(page,pages),shown=filtered.slice((safePage-1)*size,safePage*size);
 const heroVisual=settings.hero_visual_mode==='none'?null:settings.hero_visual_mode==='default'?<ThreeDArt/>:settings.hero_image_url?<img src={settings.hero_image_url} alt={settings.hero_image_alt||settings.brand_name} className="heroVisualImage" style={{objectFit:settings.hero_image_fit}}/>:<ThreeDArt/>;
 return <ThemeProvider preset={settings.theme_preset} primary={settings.primary_color} secondary={settings.secondary_color} accent={settings.accent_color}><StoreNav brand={settings.brand_name} logoUrl={settings.logo_url}/><header className="hero"><div className={`container heroGrid ${settings.hero_image_position==='left'?'visualLeft':''}`}><div className="heroCopy">{settings.hero_badge&&<span className="badge">{settings.hero_badge}</span>}<h1>{settings.hero_title}</h1><p>{settings.hero_subtitle}</p><div className="actions"><a href="#produk" className="btn">{settings.hero_primary_cta_text||'Lihat Produk'}</a>{settings.hero_member_cta_enabled&&<Link href="/member/login" className="btn soft">{settings.hero_member_cta_text||'Masuk Member'}</Link>}</div><div className="trustRow">{settings.hero_trust_1&&<span>✦ {settings.hero_trust_1}</span>}{settings.hero_trust_2&&<span>✦ {settings.hero_trust_2}</span>}{settings.hero_trust_3&&<span>✦ {settings.hero_trust_3}</span>}</div></div>{heroVisual&&<div className="heroVisualWrap">{heroVisual}</div>}</div></header><HomeBannerSlider items={banners}/>
 <section className="section" id="produk"><div className="container"><div className="sectionHead"><div>{settings.catalog_eyebrow&&<span className="eyebrow">{settings.catalog_eyebrow}</span>}<h2>{settings.catalog_title}</h2><p className="muted">{settings.catalog_subtitle}</p></div></div><div className="filterBar"><input className="input" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="Cari produk..."/><select className="input" value={cat} onChange={e=>{setCat(e.target.value);setPage(1)}}>{cats.map(c=><option key={c}>{c}</option>)}</select></div><div className="grid productGrid">{shown.map((p,i)=><article className="card productCard" key={p.id}><div className="cardFloat">{i%3===0?'✦':i%3===1?'♥':'↗'}</div>{p.image_url?<img src={p.image_url} className="productImage" alt={p.name}/>:<div className="productImage placeholderArt"><span>ADC</span></div>}<div className="cardBody"><div className="badge small">{p.category||'Produk Digital'}</div><h3>{p.name}</h3><p className="muted">{p.short_description}</p><div className="priceStack">{p.compare_at_price>p.price&&<span className="comparePrice">{rupiah(p.compare_at_price)}</span>}<div className="price">{rupiah(p.price)}</div>{p.show_discount_badge&&p.compare_at_price>p.price&&<span className="discountBadge">{p.discount_badge_text||`HEMAT ${Math.round((1-p.price/p.compare_at_price)*100)}%`}</span>}</div><Link className="btn full" href={`/product/${p.slug}`}>Lihat Detail</Link></div></article>)}{shown.length===0&&<div className="notice">Belum ada produk yang cocok.</div>}</div>{filtered.length>0&&<div className="pager3d" style={{marginTop:24}}><span>{filtered.length} produk • Halaman {safePage}/{pages} • {size} produk/halaman</span><div className="actions"><button className="btn alt" disabled={safePage<=1} onClick={()=>setPage(x=>Math.max(1,x-1))}>← Sebelumnya</button><button className="btn alt" disabled={safePage>=pages} onClick={()=>setPage(x=>Math.min(pages,x+1))}>Berikutnya →</button></div></div>}</div></section><footer className="footer"><div className="container"><div>{settings.footer_text}</div>{socials.length>0&&<div className="socialFooter">{socials.map(x=><a key={x.id} href={x.url} target="_blank" rel="noreferrer">{x.icon_url&&<img src={x.icon_url} alt=""/>}<span>{x.label||x.platform}</span></a>)}</div>}</div></footer></ThemeProvider>
}
