'use client';
import Link from 'next/link';import {useEffect,useMemo,useState} from 'react';import {useParams} from 'next/navigation';import StoreNav from '@/components/StoreNav';import ThemeProvider from '@/components/ThemeProvider';import {createClient} from '@/lib/supabase';import {Product,StoreSettings} from '@/lib/types';import {rupiah} from '@/lib/money';
const fallback:StoreSettings={id:1,brand_name:'ADCStore',tagline:'Digital Store & Affiliate Website for ADC Members',logo_url:null,whatsapp:null,instagram_url:null,primary_color:'#8b5cf6',secondary_color:'#c4b5fd',accent_color:'#f9a8d4',theme_preset:'lavender',hero_title:'Produk Digital Siap Jual untuk Member ADC',hero_subtitle:'',footer_text:'ADCStore',home_products_per_page:8};
function videoEmbed(url:string){try{const u=new URL(url);if(u.hostname.includes('youtube.com')){const id=u.searchParams.get('v');return id?`https://www.youtube.com/embed/${id}`:null}if(u.hostname==='youtu.be')return `https://www.youtube.com/embed/${u.pathname.slice(1)}`;if(u.hostname.includes('vimeo.com')){const id=u.pathname.split('/').filter(Boolean).pop();return id?`https://player.vimeo.com/video/${id}`:null}}catch{}return null}
export default function ProductDetail(){
 const {slug}=useParams<{slug:string}>();const[p,setP]=useState<Product|null>(null);const[settings,setSettings]=useState(fallback);const[loading,setLoading]=useState(true);const[activeImage,setActiveImage]=useState('');
 useEffect(()=>{const s=createClient();Promise.all([s.from('products').select('*').eq('slug',slug).eq('is_active',true).maybeSingle(),s.from('store_settings').select('*').eq('id',1).maybeSingle()]).then(([a,b])=>{const product=a.data as Product|null;if(product){product.gallery_images=product.gallery_images||[];setP(product);setActiveImage(product.image_url||product.gallery_images[0]||'')}if(b.data)setSettings({...fallback,...b.data} as StoreSettings);setLoading(false)})},[slug]);
 const gallery=useMemo(()=>p?Array.from(new Set([p.image_url,...(p.gallery_images||[])].filter(Boolean) as string[])):[],[p]);
 if(loading)return <div style={{padding:60}}>Memuat produk...</div>;if(!p)return <div style={{padding:60}}><h1>Produk tidak ditemukan</h1><Link className="btn" href="/">Kembali</Link></div>;
 const embed=p.video_url?videoEmbed(p.video_url):null;
 return <ThemeProvider preset={settings.theme_preset} primary={settings.primary_color} secondary={settings.secondary_color} accent={settings.accent_color}><StoreNav brand={settings.brand_name}/><section className="section"><div className="container"><div className="productDetail3d"><div>{activeImage?<img src={activeImage} className="productImage" alt={p.name}/>:<div className="productImage placeholderArt"><span>ADC</span></div>}{gallery.length>1&&<div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:10,marginTop:12}}>{gallery.map(url=><button key={url} onClick={()=>setActiveImage(url)} style={{border:activeImage===url?'3px solid var(--primary)':'1px solid rgba(0,0,0,.08)',padding:0,borderRadius:14,overflow:'hidden',background:'#fff',cursor:'pointer'}}><img src={url} alt="Thumbnail" style={{width:'100%',height:72,objectFit:'cover',display:'block'}}/></button>)}</div>}</div><div className="productDetailCopy"><div className="badge">{p.category||'Produk Digital'}</div><h1>{p.name}</h1><div className="price">{rupiah(p.price)}</div><p>{p.description||p.short_description}</p><div className="actions" style={{marginTop:22}}>{(p.sale_mode==='internal'||p.sale_mode==='both')&&<Link className="btn" href={`/checkout/${p.slug}`}>{p.internal_cta_text||'Checkout di Website'}</Link>}{(p.sale_mode==='affiliate'||p.sale_mode==='both')&&p.affiliate_url&&<a className="btn soft" href={p.affiliate_url} target="_blank" rel="nofollow sponsored">{p.cta_text||'Beli di Official Website'}</a>}{p.affiliate_salespage_url&&<a className="btn alt" href={p.affiliate_salespage_url} target="_blank" rel="nofollow sponsored">{p.affiliate_salespage_cta_text||'Lihat Salespage Official'}</a>}<Link className="btn alt" href="/">Kembali</Link></div>{(p.sale_mode==='affiliate'||p.sale_mode==='both')&&!p.affiliate_url&&<div className="notice" style={{marginTop:18}}>Link checkout affiliate/official belum diatur oleh pemilik toko.</div>}</div></div>
 {p.video_url&&<div className="panel3d" style={{marginTop:28,padding:22}}><span className="eyebrow">VIDEO SALES LETTER</span><div style={{marginTop:14,aspectRatio:'16 / 9',borderRadius:22,overflow:'hidden',background:'#111'}}>{embed?<iframe src={embed} title={`Video ${p.name}`} style={{width:'100%',height:'100%',border:0}} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/>:<video controls src={p.video_url} style={{width:'100%',height:'100%',objectFit:'contain'}}/>}</div></div>}
 {p.internal_salespage_html&&<div className="panel3d" style={{marginTop:28,padding:28}}><span className="eyebrow">SALESPAGE INTERNAL</span><div className="htmlPreview" dangerouslySetInnerHTML={{__html:p.internal_salespage_html}}/><div className="actions" style={{marginTop:24}}>{(p.sale_mode==='internal'||p.sale_mode==='both')&&<Link className="btn" href={`/checkout/${p.slug}`}>{p.internal_cta_text||'Checkout di Website'}</Link>}{(p.sale_mode==='affiliate'||p.sale_mode==='both')&&p.affiliate_url&&<a className="btn soft" href={p.affiliate_url} target="_blank" rel="nofollow sponsored">{p.cta_text||'Beli di Official Website'}</a>}</div></div>}</div></section></ThemeProvider>
}
