'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase';
import MediaPicker from '@/components/MediaPicker';
import { HomeBanner } from '@/lib/types';
import { ImagePlus, Pencil, Trash2, UploadCloud } from 'lucide-react';
import ConfirmDialog from '@/components/ConfirmDialog';

type Draft=Omit<HomeBanner,'id'|'created_at'|'updated_at'>;
const blank:Draft={title:'',desktop_image_url:'',mobile_image_url:'',target_url:'',cta_text:'',is_active:true,sort_order:0};
export default function Banners(){
 const[rows,setRows]=useState<HomeBanner[]>([]),[q,setQ]=useState(''),[status,setStatus]=useState('all'),[page,setPage]=useState(1),[size,setSize]=useState(10),[show,setShow]=useState(false),[edit,setEdit]=useState<HomeBanner|null>(null),[draft,setDraft]=useState<Draft>(blank),[msg,setMsg]=useState('');
 const [deleteTarget,setDeleteTarget]=useState<string|null>(null),[deleteBusy,setDeleteBusy]=useState(false);
 async function load(){const{data}=await createClient().from('homepage_banners').select('*').order('sort_order').order('created_at');setRows((data||[]) as HomeBanner[])}
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>rows.filter(x=>(status==='all'||(status==='active'&&x.is_active)||(status==='inactive'&&!x.is_active))&&`${x.title||''} ${x.target_url||''}`.toLowerCase().includes(q.toLowerCase())),[rows,q,status]);
 const pages=Math.max(1,Math.ceil(filtered.length/size)),safe=Math.min(page,pages),view=filtered.slice((safe-1)*size,safe*size);
 function openNew(){setEdit(null);setDraft(blank);setShow(true);setMsg('')}function openEdit(x:HomeBanner){setEdit(x);setDraft({title:x.title||'',desktop_image_url:x.desktop_image_url||'',mobile_image_url:x.mobile_image_url||'',target_url:x.target_url||'',cta_text:x.cta_text||'',is_active:x.is_active,sort_order:x.sort_order});setShow(true);setMsg('')}
 async function save(e:FormEvent){e.preventDefault();if(!draft.desktop_image_url){setMsg('Banner desktop wajib diisi.');return}const s=createClient();const payload={...draft,sort_order:Number(draft.sort_order)};const r=edit?await s.from('homepage_banners').update(payload).eq('id',edit.id):await s.from('homepage_banners').insert(payload);if(r.error){setMsg(r.error.message);return}setShow(false);await load()}
 async function remove(id:string){setDeleteTarget(id)}
 async function confirmDelete(){if(!deleteTarget)return;setDeleteBusy(true);const {error}=await createClient().from('homepage_banners').delete().eq('id',deleteTarget);setDeleteBusy(false);if(error){setMsg(error.message);return}setDeleteTarget(null);setMsg('Banner berhasil dihapus.');await load()}
 return <><ConfirmDialog open={!!deleteTarget} title="Hapus Banner?" message="Banner ini akan dihapus permanen." confirmText="Ya, Hapus" danger busy={deleteBusy} onCancel={()=>!deleteBusy&&setDeleteTarget(null)} onConfirm={confirmDelete}/><div className="pageHead3d"><div><span className="eyebrow">HOMEPAGE</span><h1>Slide Banner</h1><p>Kelola slider responsive. Rekomendasi desktop 1600×600 px, mobile 1080×1350 px.</p></div><button type="button" className="btn" onClick={openNew}><ImagePlus size={18}/> Tambah Banner</button></div>
 <div className="filterPanel3d"><input className="input" placeholder="Cari banner / link..." value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/><select className="input" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="all">Semua Status</option><option value="active">Aktif</option><option value="inactive">Nonaktif</option></select><select className="input" value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}><option value="10">10 / halaman</option><option value="20">20 / halaman</option><option value="50">50 / halaman</option></select></div>
 <div className="productAdminCards">{view.map(x=><article className="productAdminCard" key={x.id}><div className="productAdminThumb"><img src={x.desktop_image_url} alt={x.title||'Banner'}/></div><div className="productAdminInfo"><div className="adminCardTop"><div><span className="badge small">Banner</span><h3>{x.title||'Tanpa Judul'}</h3><small>{x.target_url||'Tanpa link tujuan'}</small></div><span className={`statusPill ${x.is_active?'paid':'cancelled'}`}>{x.is_active?'Aktif':'Nonaktif'}</span></div><div className="productAdminMeta"><span><b>{x.mobile_image_url?'Ada':'Fallback'}</b><small>Mobile</small></span><span><b>{x.cta_text||'—'}</b><small>CTA</small></span><span><b>{x.sort_order}</b><small>Urutan</small></span></div><div className="productAdminActions"><button type="button" className="btn alt" onClick={()=>openEdit(x)}><Pencil size={17}/> Edit</button><button type="button" className="btn alt dangerText" onClick={()=>remove(x.id)}><Trash2 size={17}/> Hapus</button></div></div></article>)}{!view.length&&<div className="empty3d panel3d">Belum ada banner.</div>}</div>
 <div className="pager3d"><span>{filtered.length} banner • Halaman {safe}/{pages}</span><div className="actions"><button type="button" className="btn alt" disabled={safe<=1} onClick={()=>setPage(x=>Math.max(1,x-1))}>←</button><button type="button" className="btn alt" disabled={safe>=pages} onClick={()=>setPage(x=>Math.min(pages,x+1))}>→</button></div></div>
 {show&&<div className="modalBack" onMouseDown={()=>setShow(false)}><div className="modal3d" onMouseDown={e=>e.stopPropagation()}><div className="topline"><div><span className="eyebrow">SLIDE BANNER</span><h2>{edit?'Edit Banner':'Tambah Banner'}</h2></div><button type="button" className="iconBtn3d" onClick={()=>setShow(false)}>×</button></div><form className="form" onSubmit={save}><div className="field"><label>Judul Internal</label><input className="input" value={draft.title||''} onChange={e=>setDraft({...draft,title:e.target.value})}/></div><div className="twoCols"><div className="field"><MediaPicker currentUrls={draft.desktop_image_url?[draft.desktop_image_url]:[]} label="Desktop Banner (1600×600)" onSelect={urls=>setDraft({...draft,desktop_image_url:urls[0]||''})}/><input className="input" placeholder="atau URL desktop image" value={draft.desktop_image_url} onChange={e=>setDraft({...draft,desktop_image_url:e.target.value})}/></div><div className="field"><MediaPicker currentUrls={draft.mobile_image_url?[draft.mobile_image_url]:[]} label="Mobile Banner (1080×1350)" onSelect={urls=>setDraft({...draft,mobile_image_url:urls[0]||''})}/><input className="input" placeholder="atau URL mobile image" value={draft.mobile_image_url||''} onChange={e=>setDraft({...draft,mobile_image_url:e.target.value})}/></div></div><div className="twoCols"><div className="field"><label>URL Tujuan Banner</label><input className="input" value={draft.target_url||''} onChange={e=>setDraft({...draft,target_url:e.target.value})} placeholder="https://... atau /product/slug"/></div><div className="field"><label>Teks CTA Optional</label><input className="input" value={draft.cta_text||''} onChange={e=>setDraft({...draft,cta_text:e.target.value})} placeholder="Lihat Promo"/></div></div><div className="twoCols"><div className="field"><label>Urutan</label><input className="input" type="number" value={draft.sort_order} onChange={e=>setDraft({...draft,sort_order:Number(e.target.value)})}/></div><label className="toggleLine"><input type="checkbox" checked={draft.is_active} onChange={e=>setDraft({...draft,is_active:e.target.checked})}/> Aktif</label></div>{msg&&<div className="notice">{msg}</div>}<button type="submit" className="btn">Simpan Banner</button></form></div></div>}</>
}
